<html lang="pt_BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mais1Code - Projeto</title>
    <?php require_once 'include.html' ?>
</head>

<body>
<?php include_once 'menu.phtml' ?>
<div class="container mt-2">
    <div class="text-center">
        ATENÇÃO!<br>
        Deseja realmente excluir a conta de sua empresa e todas as vagas associadas?
        <br>
        <a class="btn btn-danger" href="../processa_excluir_empresa.php">Sim, quero excluir</a>
        <a class="btn btn-secondary" href="../home.php">Cancelar</a>
    </div>
</div>


</body>
</html>