<html lang="pt_BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mais1Code - Projeto</title>
    <?php require_once 'include.html' ?>
</head>

<body>
<?php include_once 'menu.phtml' ?>
<div class="container mt-2">
    <table class="table table-bordered table-striped table-hover caption-top">
        <caption>Usuários da minha empresa</caption>
        <?php foreach ($usuarios as $usuarioAtual) : ?>
            <tr>
                <td><?= $usuarioAtual->getId(); ?></td>
                <td><?= $usuarioAtual->getCpf(); ?></td>
                <td><?= $usuarioAtual->getNome(); ?></td>
                <td><?= $usuarioAtual->getEmail(); ?></td>
                <td>
                    <a class="btn btn-primary btn-sm" href="../editar_usuario.php?id=<?= $usuarioAtual->getId() ?>">Editar</a>
                    <?php if ($usuarioAtual->getId() !== $usuario->getId()) : ?>
                        <a class="btn btn-primary btn-sm" href="../processa_excluir_usuario.php?id=<?= $usuarioAtual->getId() ?>">Excluir</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
</body>
</html>