<html lang="pt_BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mais1Code - Projeto</title>
    <?php require_once 'include.html' ?>
</head>

<body>
<?php include_once 'menu.phtml' ?>
<div class="container mt-2">
    <table class="table table-bordered table-striped table-hover caption-top">
        <caption>Minhas vagas</caption>
        <?php foreach ($vagas as $vaga) : ?>
            <tr>
                <td><?= $vaga['id'] ?></td>
                <td><?= $vaga['titulo'] ?></td>
                <td>
                    <a class="btn btn-primary btn-sm" href="../editar_vaga.php?id=<?= $vaga['id'] ?>">Editar</a>
                    <a class="btn btn-primary btn-sm" href="../processa_excluir_vaga.php?id=<?= $vaga['id'] ?>">Excluir</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
</body>
</html>