<div class="row">
    <div class="col-12">
        <hr class="mt-5 mb-4 border-secondary-subtle">
        <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-end">
            Já possui cadastro? <a href="/autenticacao/index" class="link-secondary text-decoration-none">Faça o login</a>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>

</body>
</html>