<div class="container container-sm w-75 form-bg-white pt-4 pb-4">
    <form action="/candidato/processaCadastrar" method="post">
        <input type="hidden" name="status" id="status" value="1">
        <div class="row gy-3 gy-md-4 overflow-hidden">
            <div class="col-md-6 form-floating">
                <input type="text" class="form-control" name="nome" id="nome" required>
                <label for="nome" class="form-label">Nome Completo *</label>
            </div>
            <div class="col-md-6 form-floating">
                <input type="text" class="form-control" name="cpf" id="cpf" minlength="14" maxlength="14" required>
                <label for="cpf" class="form-label">CPF *</label>
            </div>
            <div class="col-6 form-floating">
                <input type="email" class="form-control" name="email" id="email" required>
                <label for="email" class="form-label">Email</label>
            </div>
            <div class="col-6 form-floating">
                <input type="password" class="form-control" name="senha" id="senha" required>
                <label for="senha" class="form-label">Senha *</label>
            </div>
            <div class="col-12 form-floating">
                <textarea class="form-control" name="habilidades" id="habilidades" required style="min-height: 100px"></textarea>
                <label for="habilidades" class="form-label">Habilidades *</label>
            </div>
            <div class="col-12 form-floating">
                <input type="text" class="form-control" name="endereco" id="endereco" required>
                <label for="endereco" class="form-label">Endereço *</label>
            </div>
            <div class="col-3 form-floating">
                <input type="date" class="form-control" name="nascimento" id="nascimento" required>
                <label for="nascimento" class="form-label">Data de nascimento *</label>
            </div>
            <div class="col-3 form-floating">
                <select class="form-control form-select" name="disponibilidade" id="disponibilidade">
                    <option value="" disabled selected>Selecione</option>
                    <option value="3">Disponibilidade Imediata</option>
                    <option value="2">Disponível após 30 dias</option>
                    <option value="1">Tempo Parcial</option>
                    <option value="0">Tempo Integral</option>
                </select>
                <label for="disponibilidade" class="form-label">Disponibilidade *</label>
            </div>
            <div class="col-3 form-floating">
                <select class="form-control form-select" name="sexo" id="sexo">
                    <option value="" disabled selected>Selecione</option>
                    <?php foreach (SexoEnum::forSelect() as $value => $label): ?>
                        <option value="<?= $value ?>"><?= $label ?></option>
                    <?php endforeach; ?>
                </select>
                <label for="sexo" class="form-label">Sexo *</label>
            </div>
            <div class="col-3 form-floating">
                <select class="form-control form-select" name="genero" id="genero">
                    <option value="" disabled selected>Selecione</option>
                    <option value="C">Cisgênero</option>
                    <option value="T">Transgênero</option>
                    <option value="O">Outro</option>
                </select>
                <label for="genero" class="form-label">Gênero *</label>
            </div>
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit">Cadastrar</button>
                </div>
            </div>
        </div>
    </form>
</div>
