<div class="overflow-x-auto flex justify-center w-full mb-10 mt-5">
    <table class="border-collapse table-sm table-zebra border-collapse dark:border-slate-500 bg-white dark:bg-slate-800 text-sm shadow-sm w-3/5">
        <caption class="text-slate-500 dark:text-slate-400 pb-4 text-md caption-top">
            <div class="flex">
                <div class="w-full flex items-center justify-start">
                    <h2 class="">Minhas vagas</h2>
                </div>
            </div>
        </caption>
        <thead class="bg-slate-50 dark:bg-slate-700">
        <tr>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">#</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Título</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Empresa</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Status da vaga</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Status da candidatura</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">
                <div class="flex justify-center items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
                        <path fill-rule="evenodd" d="M6.955 1.45A.5.5 0 0 1 7.452 1h1.096a.5.5 0 0 1 .497.45l.17 1.699c.484.12.94.312 1.356.562l1.321-1.081a.5.5 0 0 1 .67.033l.774.775a.5.5 0 0 1 .034.67l-1.08 1.32c.25.417.44.873.561 1.357l1.699.17a.5.5 0 0 1 .45.497v1.096a.5.5 0 0 1-.45.497l-1.699.17c-.12.484-.312.94-.562 1.356l1.082 1.322a.5.5 0 0 1-.034.67l-.774.774a.5.5 0 0 1-.67.033l-1.322-1.08c-.416.25-.872.44-1.356.561l-.17 1.699a.5.5 0 0 1-.497.45H7.452a.5.5 0 0 1-.497-.45l-.17-1.699a4.973 4.973 0 0 1-1.356-.562L4.108 13.37a.5.5 0 0 1-.67-.033l-.774-.775a.5.5 0 0 1-.034-.67l1.08-1.32a4.971 4.971 0 0 1-.561-1.357l-1.699-.17A.5.5 0 0 1 1 8.548V7.452a.5.5 0 0 1 .45-.497l1.699-.17c.12-.484.312-.94.562-1.356L2.629 4.107a.5.5 0 0 1 .034-.67l.774-.774a.5.5 0 0 1 .67-.033L5.43 3.71a4.97 4.97 0 0 1 1.356-.561l.17-1.699ZM6 8c0 .538.212 1.026.558 1.385l.057.057a2 2 0 0 0 2.828-2.828l-.058-.056A2 2 0 0 0 6 8Z" clip-rule="evenodd"/>
                    </svg>
                </div>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        /** @var array<CandidatoVaga> $vagasCandidatadas */
        foreach ($vagasCandidatadas as $vaga) : ?>
            <tr class="hover">
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getVaga()->getId() ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getVaga()->getTitulo() ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getVaga()->getEmpresa()->getNome() ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getVaga()->getStatus(true) ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getStatus(true) ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400">
                    <div class="flex justify-center space-x-2">
                        <div class="tooltip" data-tip="Ver detalhes da vaga">
                            <a href="/vaga/exibir?id=<?= $vaga->getVaga()->getId() ?>" class="btn btn-xs h-8 w-8 border btn-square border-accent-content/15" target="_blank">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"/>
                                </svg>
                            </a>
                        </div>
                        <?php
                        /** @var array<Proposta> $propostas */
                        foreach ($propostas as $proposta) : ?>
                            <?php if (!empty($proposta) && $proposta->getVaga()->getId() == $vaga->getVaga()->getId() && $proposta->getAceite() == PropostaStatusEnum::Aguardando->value) : ?>
                                <div class="tooltip" data-tip="Ver proposta">
                                    <a href="/proposta/exibir?vagaId=<?= 1 //$proposta->getVaga()->getId() ?? '1'        ?>" class="btn btn-xs btn-success h-8 w-8 border btn-square border-accent-content/15">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m5.231 13.481L15 17.25m-4.5-15H5.625c-.621 0-1.125.504-1.125 1.125v16.5c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Zm3.75 11.625a2.625 2.625 0 1 1-5.25 0 2.625 2.625 0 0 1 5.25 0Z"/>
                                        </svg>
                                    </a>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
