<div class="mx-auto max-w-7xl border pb-10 rounded-xl bg-white mt-10">
    <div class="overflow-x-auto flex justify-center w-full">
        <table class="border-collapse table-md table-zebra border-collapse border border-slate-400 dark:border-slate-500 bg-white dark:bg-slate-800 text-sm shadow-sm">
            <caption class="text-slate-500 dark:text-slate-400 pb-4 text-md caption-top p-4">Minhas vagas</caption>
            <thead class="bg-slate-50 dark:bg-slate-700">
            <tr>
                <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">#</th>
                <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Título</th>
                <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Empresa</th>
                <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Status da vaga</th>
                <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Status da candidatura</th>
                <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">
                    <div class="flex justify-center items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
                            <path fill-rule="evenodd" d="M6.955 1.45A.5.5 0 0 1 7.452 1h1.096a.5.5 0 0 1 .497.45l.17 1.699c.484.12.94.312 1.356.562l1.321-1.081a.5.5 0 0 1 .67.033l.774.775a.5.5 0 0 1 .034.67l-1.08 1.32c.25.417.44.873.561 1.357l1.699.17a.5.5 0 0 1 .45.497v1.096a.5.5 0 0 1-.45.497l-1.699.17c-.12.484-.312.94-.562 1.356l1.082 1.322a.5.5 0 0 1-.034.67l-.774.774a.5.5 0 0 1-.67.033l-1.322-1.08c-.416.25-.872.44-1.356.561l-.17 1.699a.5.5 0 0 1-.497.45H7.452a.5.5 0 0 1-.497-.45l-.17-1.699a4.973 4.973 0 0 1-1.356-.562L4.108 13.37a.5.5 0 0 1-.67-.033l-.774-.775a.5.5 0 0 1-.034-.67l1.08-1.32a4.971 4.971 0 0 1-.561-1.357l-1.699-.17A.5.5 0 0 1 1 8.548V7.452a.5.5 0 0 1 .45-.497l1.699-.17c.12-.484.312-.94.562-1.356L2.629 4.107a.5.5 0 0 1 .034-.67l.774-.774a.5.5 0 0 1 .67-.033L5.43 3.71a4.97 4.97 0 0 1 1.356-.561l.17-1.699ZM6 8c0 .538.212 1.026.558 1.385l.057.057a2 2 0 0 0 2.828-2.828l-.058-.056A2 2 0 0 0 6 8Z" clip-rule="evenodd"/>
                        </svg>
                    </div>
                </th>
                <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Propostas</th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var array<CandidatoVaga> $vagasCandidatadas */
            foreach ($vagasCandidatadas as $vaga) : ?>
                <tr class="hover">
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getVaga()->getId() ?></td>
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getVaga()->getTitulo() ?></td>
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getVaga()->getEmpresa()->getNome() ?></td>
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getVaga()->getStatus(true) ?></td>
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $vaga->getStatus(true) ?></td>
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400">
                        <a href="/vaga/exibir?id=<?= $vaga->getVaga()->getId() ?>" title="Ver" class="flex justify-center items-center ">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m15.75 15.75-2.489-2.489m0 0a3.375 3.375 0 1 0-4.773-4.773 3.375 3.375 0 0 0 4.774 4.774ZM21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                            </svg>
                        </a>
                    </td>
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400">
                        <?php 
                        /** @var array<Propostas> $propostas */
                        foreach ($propostas as $proposta) : ?>
                            <?php if (!empty($proposta) && $proposta->getVaga()->getId() == $vaga->getVaga()->getId()) : ?>
                                <a class="btn btn-primary" href="/proposta/exibir?vagaId=<?=$proposta->getVaga()->getId()?>">Detalhes</a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
