    <table class="table table-bordered table-striped table-hover caption-top">
        <caption>Minhas vagas</caption>
        <thead>
            <tr>
                <th class="minimal">#</th>
                <th>Título</th>
                <th>Empresa</th>
                <th>Status da vaga</th>
                <th class="minimal"><i class="fas fa-cog"></i></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($vagasCandidatadas as $vaga) : ?>
            <tr>
                <td class="minimal"><?= $vaga->getVaga()->getId() ?></td>
                <td><?= $vaga->getVaga()->getTitulo() ?></td>
                <td><?= $vaga->getVaga()->getEmpresa()->getNome() ?></td>
                <td><?= $vaga->getVaga()->getStatus(true) ?></td>
                <td class="minimal">
                    <a class="btn btn-primary btn-sm" href="/vaga/exibir?id=<?= $vaga->getVaga()->getId() ?>" title=""><i class="fas fa-search"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>