<?php if (isset($_SESSION['error'])) : ?>
    <div class="col-12">
        <?= $_SESSION['error'] ?>
    </div>
<?php endif; ?>

<h4>Área do candidato</h4>
<form action="/candidato/processaLogin" method="post" onsubmit="verificaDados()">
<?php if (!empty($_SESSION['CadastroRealizado'])) : ?>
    <div>
        <?=$_SESSION['CadastroRealizado'];?>
    </div>
<?php endif; ?>
    <div class="row gy-3 gy-md-4 overflow-hidden mt-5">
        <div class="col-12">
            <label for="email" class="form-label">Email
                <span>*</span></label>
            <input type="email" class="form-control" name="email" id="email" maxlength="30" placeholder="Informe seu e-mail de acesso" required>
        </div>
        <div class="col-12">
            <label for="senha" class="form-label">Senha
                <span>*</span></label>
            <input type="password" class="form-control" name="senha" id="senha" minlength="8" value="" placeholder="*****" required>
        </div>
        <div class="col-12 d-flex justify-content-between">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" name="remember_me" id="remember_me">
                <label class="form-check-label" for="remember_me">
                    Mantenha-me logado
                </label>
            </div>
            <a href="/candidato/esqueci-senha" class="link-secondary text-decoration-none">Esqueci minha senha</a>
        </div>
        <div class="col-12">
            <div class="d-grid">
                <button id="icon-button" class="btn btn-primary" type="submit">
                    <i class="fas fa-lock icon-transition"></i>
                    <i class="fas fa-lock-open icon-transition" style="display: none;"></i>
                    Acessar
                </button>
            </div>
        </div>
    </div>
</form>


<div class="row">
    <div class="col-12">
        <hr class="mt-5 mb-4 border-secondary-subtle">
        <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-between">
            <a href="/" class="link-secondary text-decoration-none">Painel de vagas</a>
            <a href="/candidato/cadastrar" class="link-secondary text-decoration-none">Criar minha conta</a>
        </div>
    </div>
</div>
<script>

    function verificaDados() {

        let email = document.getElementById('email').value;
        let senha = document.getElementById('senha').value;

        if (email === '' || senha === '') {
            alert("login falhou");
            return false;
        } else {
            alert("login concluido");
        }

    }

    document.addEventListener('DOMContentLoaded', (event) => {
        const button = document.getElementById('icon-button');
        const lockIcon = button.querySelector('.fa-lock');
        const lockOpenIcon = button.querySelector('.fa-lock-open');

        button.addEventListener('mouseenter', () => {
            lockIcon.style.display = 'none';
            lockOpenIcon.style.display = '';
        });

        button.addEventListener('mouseleave', () => {
            lockIcon.style.display = '';
            lockOpenIcon.style.display = 'none';

        });
    });
</script>

