<div class="overflow-x-auto flex justify-center w-full mb-10 mt-5">
    <table class="border-collapse table-sm table-zebra border-collapse dark:border-slate-500 bg-white dark:bg-slate-800 text-sm shadow-sm w-3/5">
        <caption class="text-slate-500 dark:text-slate-400 pb-4 text-md caption-top">
            <div class="flex">
                <div class="w-full flex items-center justify-start">
                    <h2 class="">Minhas Notificações</h2>
                </div>
            </div>
        </caption>
        <thead class="bg-slate-50 dark:bg-slate-700">
        <tr>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200">Mensagem</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200 whitespace-nowrap w-0">
                <div class="flex justify-center items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
                        <path fill-rule="evenodd" d="M6.955 1.45A.5.5 0 0 1 7.452 1h1.096a.5.5 0 0 1 .497.45l.17 1.699c.484.12.94.312 1.356.562l1.321-1.081a.5.5 0 0 1 .67.033l.774.775a.5.5 0 0 1 .034.67l-1.08 1.32c.25.417.44.873.561 1.357l1.699.17a.5.5 0 0 1 .45.497v1.096a.5.5 0 0 1-.45.497l-1.699.17c-.12.484-.312.94-.562 1.356l1.082 1.322a.5.5 0 0 1-.034.67l-.774.774a.5.5 0 0 1-.67.033l-1.322-1.08c-.416.25-.872.44-1.356.561l-.17 1.699a.5.5 0 0 1-.497.45H7.452a.5.5 0 0 1-.497-.45l-.17-1.699a4.973 4.973 0 0 1-1.356-.562L4.108 13.37a.5.5 0 0 1-.67-.033l-.774-.775a.5.5 0 0 1-.034-.67l1.08-1.32a4.971 4.971 0 0 1-.561-1.357l-1.699-.17A.5.5 0 0 1 1 8.548V7.452a.5.5 0 0 1 .45-.497l1.699-.17c.12-.484.312-.94.562-1.356L2.629 4.107a.5.5 0 0 1 .034-.67l.774-.774a.5.5 0 0 1 .67-.033L5.43 3.71a4.97 4.97 0 0 1 1.356-.561l.17-1.699ZM6 8c0 .538.212 1.026.558 1.385l.057.057a2 2 0 0 0 2.828-2.828l-.058-.056A2 2 0 0 0 6 8Z" clip-rule="evenodd"/>
                    </svg>
                </div>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        /** @var array<Notificacoes> $notificacoes */
        foreach ($notificacoes as $notificacao) : ?>
            <tr class="hover">
                <?php if ($notificacao->getStatus() !== NotificacoesStatusEnum::Inativa->value) : ?>
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400">
                        <div class=" mb-1">
                            <span class="text-xs font-bold"><?= $notificacao->getEmpresa()->getNome() ?></span> em
                            <span class="text-xs font-bold mb-1"><?= date("d/m/Y, H:i:s", strtotime($notificacao->getDataHora())) ?></span>
                        </div>
                        <div class="truncate"><?= $notificacao->getTitulo() ?></div>
                    </td>
                    <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400">
                        <div class="flex justify-center space-x-1">
                            <button <?= !empty($notificacao->getDescricao()) ? "" : "disabled" ?> class="btn btn-xs h-8 w-8 border btn-square border-accent-content/15" title="Excluir" onclick="modal_notificacao_<?= $notificacao->getId() ?>.showModal()">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"/>
                                </svg>
                            </button>
                            <?php if ($notificacao->getStatus() !== NotificacoesStatusEnum::Lida->value) : ?>
                                <a class="btn btn-xs h-8 w-8 border btn-square border-accent-content/15 icon-button_candidato" title="Marcar como lida" href="/notificacoes/alterar?id=<?= $notificacao->getId() ?>&indice=1">
                                    <label class="swap">
                                        <input type="checkbox" name="swap-icon-button_candidato"/>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="swap-off h-5 w-5 size-5">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75"/>
                                        </svg>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="swap-on h-5 w-5 size-5">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 9v.906a2.25 2.25 0 0 1-1.183 1.981l-6.478 3.488M2.25 9v.906a2.25 2.25 0 0 0 1.183 1.981l6.478 3.488m8.839 2.51-4.66-2.51m0 0-1.023-.55a2.25 2.25 0 0 0-2.134 0l-1.022.55m0 0-4.661 2.51m16.5 1.615a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V8.844a2.25 2.25 0 0 1 1.183-1.981l7.5-4.039a2.25 2.25 0 0 1 2.134 0l7.5 4.039a2.25 2.25 0 0 1 1.183 1.98V19.5Z"/>
                                        </svg>
                                    </label>
                                </a>
                            <?php else: ?>
                                <button disabled class="btn btn-xs h-8 w-8 border btn-square border-accent-content/15" title="Marcar como lida">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 9v.906a2.25 2.25 0 0 1-1.183 1.981l-6.478 3.488M2.25 9v.906a2.25 2.25 0 0 0 1.183 1.981l6.478 3.488m8.839 2.51-4.66-2.51m0 0-1.023-.55a2.25 2.25 0 0 0-2.134 0l-1.022.55m0 0-4.661 2.51m16.5 1.615a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V8.844a2.25 2.25 0 0 1 1.183-1.981l7.5-4.039a2.25 2.25 0 0 1 2.134 0l7.5 4.039a2.25 2.25 0 0 1 1.183 1.98V19.5Z"/>
                                    </svg>
                                </button>
                            <?php endif; ?>
                            <a class="btn btn-xs h-8 w-8 border btn-square border-accent-content/15 text-error" title="Excluir" href="/notificacoes/alterar?id=<?= $notificacao->getId() ?>&indice=2">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/>
                                </svg>
                            </a>
                        </div>
                    </td>
                <?php endif; ?>
            </tr>
            <dialog id="modal_notificacao_<?= $notificacao->getId() ?>" class="modal">
                <div class="modal-box">
                    <div class="flex justify-between gap-4">
                        <h2 class="font-bold text-lg"><?= $notificacao->getTitulo() ?></h2>
                    </div>
                    <div class="items-center gap-1">
                        <span class="font-medium text-xs uppercase text-accent">Descrição:</span>
                        <p class="py-4"><?= $notificacao->getDescricao() ?></p>
                    </div>
                    <div class="modal-action">
                        <form method="dialog">
                            <!-- if there is a button in form, it will close the modal -->
                            <button class="btn btn-ghost">Fechar</button>
                        </form>
                    </div>
                </div>
            </dialog>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        let ancoras = document.querySelectorAll('.icon-button_candidato');
        ancoras.forEach(function (ancora) {
            console.log(ancora)
            let iconbutton = ancora.querySelector("input[name='swap-icon-button_candidato']")
            ancora.addEventListener('mouseenter', () => iconbutton.checked = true);
            ancora.addEventListener('mouseleave', () => iconbutton.checked = false);
        })
    });
</script>