<div class="mx-auto max-w-2xl border p-4 m-14 rounded-xl bg-white">
    <form method="post" action="/candidato/salvarSenha">
        <div class="flex space-x-2">
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Digite a nova senha</span>
                </div>
                <input type="password" name="senha" id="senha" required minlength="8" class="input input-bordered w-full"/>
            </label>
        </div>


        <div class="mt-6 flex items-center justify-end">
            <button class="btn btn-success btn-block" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                </svg>
                Salvar
            </button>
        </div>
    </form>
</div>