
                        <form action="/autenticacao/processaLogin" method="post">
                            <div class="row gy-3 gy-md-4 overflow-hidden">
                                <div class="col-12">
                                    <label for="email" class="form-label">Email
                                        <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" name="email" id="email" placeholder="Informe seu e-mail de acesso" required>
                                </div>
                                <div class="col-12">
                                    <label for="senha" class="form-label">Senha
                                        <span class="text-danger">*</span></label>
                                    <input type="password" class="form-control" name="senha" id="senha" value="" required>
                                </div>
                                <div class="col-12">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" name="remember_me" id="remember_me">
                                        <label class="form-check-label text-secondary" for="remember_me">
                                            Mantenha-me logado
                                        </label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="d-grid">
                                        <button class="btn bsb-btn-xl btn-primary" type="submit">Acessar</button>
                                    </div>
                                </div>
                            </div>
                        </form>
