<div class="container container-md w-50">
    <form method="post" action="/beneficio/processaCadastrar">
        <div class="row g-3 align-items-center mb-2">
            <input type="hidden" name="id" value=""/>
            <div class="col-md-12 form-floating">
                <input type="text" class="form-control" name="beneficio" id="beneficio" value="" required>
                <label for="beneficio" class="col-form-label">Beneficio</label>
            </div>
        </div>
        <div class="row gy-3 gy-md-4 overflow-hidden mt-4 mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>