<div class="container container-sm w-75 form-bg-white pt-4 pb-4">
    <h4>Vaga #<?= $vaga->getId() ?></h4>
    <br>
    <h1><?= $vaga->getTitulo() ?></h1>
    <h5><?= $vaga->getEmpresa()->getNome() ?></h5>
    <br>
    <p>Salário: R$ <?= $vaga->getSalario() ?></p>
    <p>Benefícios: <?= $vaga->getBeneficios() ?></p>
    <p>Descrição: <?= $vaga->getDescricao() ?></p>
    <p>Requisitos: <?= $vaga->getRequisitos() ?></p>
    <p>Carga Horária: <?= $vaga->getCargaHoraria() ?></p>
    <p>Regime de Contratação: <?= RegimeContratacaoEnum::from($vaga->getRegimeContratacao())->label() ?></p>
    <p>Regime de Trabalho: <?= RegimeTrabalhoEnum::from($vaga->getRegimeTrabalho())->label() ?></p>
    <p>Senioridade: <?= NivelSenioridadeEnum::from($vaga->getNivelSenioridade())->label() ?></p>
    <p>Hierarquia: <?= NivelHierarquicoEnum::from($vaga->getNivelHierarquico())->label() ?></p>
    <br>
    <div>
        <?php if ($vaga->getStatus() == VagaStatusEnum::Ativa->value): ?>
            <?php if (CandidatoController::estaLogado()): ?>
                <?php if (empty($candidato_vaga)) : ?>
                    <a class="btn btn-primary" href="/vaga/processaCandidatura?id=<?= $vaga->getId() ?>">Quer se candidatar? Clique aqui </a>
                <?php else: ?>
                    <?php if ($candidato_vaga->getStatus() !== CandidatoVagaStatusEnum::Desistencia->value) : ?>
                        <a class="btn btn-primary" href="/vaga/desistirCandidatura?id=<?= $vaga->getId() ?>">Deseja desistir da candidatura?</a>
                    <?php else : ?>
                        <?php if ($candidato_vaga->desistenciaLiberada()): ?>
                            <a class="btn btn-primary" href="/vaga/processaCandidatura?id=<?= $vaga->getId() ?>">Quer se candidatar? Clique aqui </a>
                        <?php else : ?>
                            <button class="btn btn-primary">Aguarde 24 horas, para candidatar-se novamente!</button>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif ?>
            <?php else: ?>
                <a class="btn btn-primary" href="/candidato/login">Quer se candidatar? Efetue Login</a>
            <?php endif; ?>
        <?php else: ?>
            <button class="btn btn-secondary">Essa vaga já foi encerrada. =(</button>
        <?php endif; ?>
    </div>
</div>
