<?php /** @var Vaga $vaga */ ?>
<div class="max-w-screen-lg mx-auto px-4 xl:px-0 pt-5 pb-10">
    <div class="breadcrumbs text-sm">
        <ul>
            <li>
                <a href="/">Home</a>
            </li>
            <li>
                <a href="/#vagas">Vagas</a>
            </li>
            <li><?= $vaga->getTitulo() ?></li>
        </ul>
    </div>
    <div class="flex justify-end">
        <?php if ($vaga->getStatus() == VagaStatusEnum::Ativa->value) : ?>
            <?php if (CandidatoController::estaLogado()) : ?>
                <?php if (empty($candidato_vaga)) : ?>
                    <a class="btn btn-primary" href="/vaga/processaCandidatura?id=<?= $vaga->getId() ?>">Quer se candidatar? Clique aqui </a>
                <?php else : ?>
                    <?php if ($candidato_vaga->getStatus() !== CandidatoVagaStatusEnum::Desistencia->value) : ?>
                        <a class="btn btn-primary" href="/vaga/desistirCandidatura?id=<?= $vaga->getId() ?>">Deseja desistir da candidatura?</a>
                    <?php else : ?>
                        <?php if ($candidato_vaga->desistenciaLiberada()) : ?>
                            <a class="btn btn-primary" href="/vaga/processaCandidatura?id=<?= $vaga->getId() ?>">Quer se candidatar? Clique aqui </a>
                        <?php else : ?>
                            <div role="alert" class="alert alert-info flex">
                                <svg class="w-5 h-5" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                    <path clip-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 6a.75.75 0 0 0-1.5 0v6c0 .414.336.75.75.75h4.5a.75.75 0 0 0 0-1.5h-3.75V6Z" fill-rule="evenodd"></path>
                                </svg>
                                <span>Aguarde 24 horas, para candidatar-se novamente!</span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif ?>
            <?php else : ?>
                <a class="btn btn-primary" href="/candidato/login">Quer se candidatar? Efetue Login</a>
            <?php endif; ?>
        <?php else : ?>
            <div role="alert" class="alert alert-warning flex">
                <svg class="w-5 h-5" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path clip-rule="evenodd" d="M12 1.5a5.25 5.25 0 0 0-5.25 5.25v3a3 3 0 0 0-3 3v6.75a3 3 0 0 0 3 3h10.5a3 3 0 0 0 3-3v-6.75a3 3 0 0 0-3-3v-3c0-2.9-2.35-5.25-5.25-5.25Zm3.75 8.25v-3a3.75 3.75 0 1 0-7.5 0v3h7.5Z" fill-rule="evenodd"></path>
                </svg>
                <span>Essa vaga já foi encerrada. =(</span>
            </div>
        <?php endif; ?>
    </div>
    <div class="px-4 py-2 bg-base-100 shadow rounded-lg mt-4 flex justify-between items-center gap-4">
        <div>
            <h1 class="font-medium"><?= $vaga->getTitulo() ?></h1>
            <span class="font-medium uppercase text-accent"><?= $vaga->getEmpresa()->getNome() ?></span>
        </div>
        <div class="h-14 w-14">
            <img src="/assets/images/emblema-branco.png" width="56" height="56" class="object-cover w-full h-full rounded-full" alt="Logo Empresa X"/>
        </div>
    </div>
    <div class="px-4 pt-2 pb-4 bg-base-100 shadow rounded-lg mt-4 flex flex-col gap-4">
        <h2>Detalhes</h2>
        <div class="flex flex-wrap gap-x-4 gap-y-2">
            <div class="flex items-center gap-1">
                <svg class="w-6 h-6" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10.464 8.746c.227-.18.497-.311.786-.394v2.795a2.252 2.252 0 0 1-.786-.393c-.394-.313-.546-.681-.546-1.004 0-.323.152-.691.546-1.004ZM12.75 15.662v-2.824c.347.085.664.228.921.421.427.32.579.686.579.991 0 .305-.152.671-.579.991a2.534 2.534 0 0 1-.921.42Z"></path>
                    <path clip-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 6a.75.75 0 0 0-1.5 0v.816a3.836 3.836 0 0 0-1.72.756c-.712.566-1.112 1.35-1.112 2.178 0 .829.4 1.612 1.113 2.178.502.4 1.102.647 1.719.756v2.978a2.536 2.536 0 0 1-.921-.421l-.879-.66a.75.75 0 0 0-.9 1.2l.879.66c.533.4 1.169.645 1.821.75V18a.75.75 0 0 0 1.5 0v-.81a4.124 4.124 0 0 0 1.821-.749c.745-.559 1.179-1.344 1.179-2.191 0-.847-.434-1.632-1.179-2.191a4.122 4.122 0 0 0-1.821-.75V8.354c.29.082.559.213.786.393l.415.33a.75.75 0 0 0 .933-1.175l-.415-.33a3.836 3.836 0 0 0-1.719-.755V6Z" fill-rule="evenodd"></path>
                </svg>
                <span>R$ <?= $vaga->getSalario() ?></span>
            </div>
            <div class="flex items-center gap-1">
                <svg class="w-6 h-6" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path clip-rule="evenodd" d="M7.5 5.25a3 3 0 0 1 3-3h3a3 3 0 0 1 3 3v.205c.933.085 1.857.197 2.774.334 1.454.218 2.476 1.483 2.476 2.917v3.033c0 1.211-.734 2.352-1.936 2.752A24.726 24.726 0 0 1 12 15.75c-2.73 0-5.357-.442-7.814-1.259-1.202-.4-1.936-1.541-1.936-2.752V8.706c0-1.434 1.022-2.7 2.476-2.917A48.814 48.814 0 0 1 7.5 5.455V5.25Zm7.5 0v.09a49.488 49.488 0 0 0-6 0v-.09a1.5 1.5 0 0 1 1.5-1.5h3a1.5 1.5 0 0 1 1.5 1.5Zm-3 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z" fill-rule="evenodd"></path>
                    <path d="M3 18.4v-2.796a4.3 4.3 0 0 0 .713.31A26.226 26.226 0 0 0 12 17.25c2.892 0 5.68-.468 8.287-1.335.252-.084.49-.189.713-.311V18.4c0 1.452-1.047 2.728-2.523 2.923-2.12.282-4.282.427-6.477.427a49.19 49.19 0 0 1-6.477-.427C4.047 21.128 3 19.852 3 18.4Z"></path>
                </svg>
                <span><?= RegimeContratacaoEnum::from($vaga->getRegimeContratacao())->label() ?> - <?= RegimeTrabalhoEnum::from($vaga->getRegimeTrabalho())->label() ?></span>
            </div>
            <div class="flex items-center gap-1">
                <svg class="w-6 h-6" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path clip-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 6a.75.75 0 0 0-1.5 0v6c0 .414.336.75.75.75h4.5a.75.75 0 0 0 0-1.5h-3.75V6Z" fill-rule="evenodd"></path>
                </svg>
                <span><?= $vaga->getCargaHoraria() ?> horas/mês</span>
            </div>
            <div class="flex items-center gap-1">
                <svg class="w-6 h-6" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path clip-rule="evenodd" d="M8.25 6.75a3.75 3.75 0 1 1 7.5 0 3.75 3.75 0 0 1-7.5 0ZM15.75 9.75a3 3 0 1 1 6 0 3 3 0 0 1-6 0ZM2.25 9.75a3 3 0 1 1 6 0 3 3 0 0 1-6 0ZM6.31 15.117A6.745 6.745 0 0 1 12 12a6.745 6.745 0 0 1 6.709 7.498.75.75 0 0 1-.372.568A12.696 12.696 0 0 1 12 21.75c-2.305 0-4.47-.612-6.337-1.684a.75.75 0 0 1-.372-.568 6.787 6.787 0 0 1 1.019-4.38Z" fill-rule="evenodd"></path>
                    <path d="M5.082 14.254a8.287 8.287 0 0 0-1.308 5.135 9.687 9.687 0 0 1-1.764-.44l-.115-.04a.563.563 0 0 1-.373-.487l-.01-.121a3.75 3.75 0 0 1 3.57-4.047ZM20.226 19.389a8.287 8.287 0 0 0-1.308-5.135 3.75 3.75 0 0 1 3.57 4.047l-.01.121a.563.563 0 0 1-.373.486l-.115.04c-.567.2-1.156.349-1.764.441Z"></path>
                </svg>
                <span><?= NivelHierarquicoEnum::from($vaga->getNivelHierarquico())->label() ?> - <?= NivelSenioridadeEnum::from($vaga->getNivelSenioridade())->label() ?></span>
            </div>
        </div>
        <p class="mt-2"><?= $vaga->getDescricao() ?></p>
        <div class="flex flex-wrap gap-2">
            <span class="text-base">Habilidades:</span>
            <?php foreach ($vaga->getHabilidades() as $habilidade) : ?>
                <span class="badge badge-primary"><?= $habilidade->getHabilidade() ?></span>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="px-4 pt-2 pb-4 bg-base-100 shadow rounded-lg mt-4 flex flex-col gap-4">
        <h2>Benefícios</h2>
        <?php foreach ($vaga->getBeneficios() as $vagaBeneficio) :
            $beneficio = BeneficioDTO::recuperar($vagaBeneficio->getBeneficioId());
            ?>
            <div class="flex flex-wrap gap-2 items-center">
                <span class="text-base"><?= $beneficio->getNome() ?><?=!empty($vagaBeneficio->getInformacao()) ? ": {$vagaBeneficio->getInformacao()}" : ""?></span>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="px-4 pt-2 pb-4 bg-base-100 shadow rounded-lg mt-4 flex flex-col gap-4">
        <h2>Localização</h2>
        <div class="flex flex-wrap gap-x-4 gap-y-2">
            <div class="flex items-center gap-1">
                <svg class="w-6 h-6" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path clip-rule="evenodd" d="m11.54 22.351.07.04.028.016a.76.76 0 0 0 .723 0l.028-.015.071-.041a16.975 16.975 0 0 0 1.144-.742 19.58 19.58 0 0 0 2.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 0 0-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 0 0 2.682 2.282 16.975 16.975 0 0 0 1.145.742ZM12 13.5a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" fill-rule="evenodd"></path>
                </svg>
                <span><?= "{$vaga->getFilial()->getBairro()} - {$vaga->getFilial()->getCidade()}, {$vaga->getFilial()->getEstado()}" ?></span>
                <a target="_blank" href="https://www.google.com/maps/search/?api=1&query=<?= join("+", [$vaga->getFilial()->getBairro(), $vaga->getFilial()->getCidade(), $vaga->getFilial()->getEstado()]) ?>">
                    <svg class="w-6 h-6" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9 6.75V15m6-6v8.25m.503 3.498 4.875-2.437c.381-.19.622-.58.622-1.006V4.82c0-.836-.88-1.38-1.628-1.006l-3.869 1.934c-.317.159-.69.159-1.006 0L9.503 3.252a1.125 1.125 0 0 0-1.006 0L3.622 5.689C3.24 5.88 3 6.27 3 6.695V19.18c0 .836.88 1.38 1.628 1.006l3.869-1.934c.317-.159.69-.159 1.006 0l4.994 2.497c.317.158.69.158 1.006 0Z"/>
                    </svg>
                </a>
            </div>
        </div>
    </div>
</div>