<div class="container container-sm w-75">
    <form method="post" action="/vaga/salvar">
        <input type="hidden" name="vagaId" value="<?= isset($vaga) ? $vaga->getId() : '' ?>"/>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-12 form-floating">
                <input type="text" class="form-control" name="titulo" id="titulo" value="<?= isset($vaga) ? $vaga->getTitulo() : '' ?>">
                <label for="titulo" class="col-form-label">Título</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-4 form-floating">
                <input type="text" class="form-control" name="email" id="email" value="<?= isset($vaga) ? $vaga->getEmail() : '' ?>">
                <label for="email" class="col-form-label">Email</label>
            </div>

            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-text">R$</span>
                    <div class="form-floating">
                        <input type="number" class="form-control" name="salario" id="salario" value="<?= isset($vaga) ? $vaga->getSalario() : '' ?>" min="0">
                        <label for="salario" class="col-form-label">Salário</label>
                    </div>
                </div>
            </div>

            <div class="col-md-4 form-floating">
                <input type="number" class="form-control" name="cargaHoraria" id="cargaHoraria" value="<?= isset($vaga) ? $vaga->getCargaHoraria() : '' ?>" min="0">
                <label for="cargaHoraria" class="col-form-label">Carga horária</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-12 form-floating">
                <textarea class="form-control" cols="50" name="descricao" id="descricao" style="min-height: 100px;"><?= isset($vaga) ? $vaga->getDescricao() : '' ?></textarea>
                <label for="descricao" class="col-form-label">Descrição</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-6 form-floating">
                <textarea class="form-control" name="beneficios" id="beneficios" style="min-height: 100px;"><?= isset($vaga) ? $vaga->getBeneficios() : '' ?></textarea>
                <label for="beneficios" class="col-form-label">Benefícios</label>
            </div>
            <div class="col-md-6 form-floating">
                <textarea class="form-control" cols="50" name="requisitos" id="requisitos" style="min-height: 100px;"><?= isset($vaga) ? $vaga->getRequisitos() : '' ?></textarea>
                <label for="requisitos" class="col-form-label">Requisitos</label>
            </div>
        </div>

        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-3 form-floating">
                <select class="form-control form-select" name="status" id="status">
                    <option value="1" <?= !empty($vaga) && $vaga->getStatus() == '1' ? 'selected' : '' ?>>Ativa</option>
                    <?php if (!empty($vaga)) : ?>
                        <option value="0" <?= !empty($vaga) && $vaga->getStatus() == '0' ? 'selected' : '' ?>>Inativa</option>
                    <?php endif; ?>
                </select>
                <label for="status" class="col-form-label">Status</label>
            </div>
            <!-- REGIME DE CONTRATAÇÃO -->
            <div class="col-md-3 form-floating">
                <select class="form-control form-select" name="regimeContratacao" id="regimeContratacao">
                    <option value="0" required >Selecione</option>
                        <option value="1" <?= !empty($vaga) && $vaga->getRegimeContratacao() == '1' ? 'selected' : '' ?>>CLT</option>
                        <option value="2" <?= !empty($vaga) && $vaga->getRegimeContratacao() == '2' ? 'selected' : '' ?>>PJ</option>
                        <option value="3" <?= !empty($vaga) && $vaga->getRegimeContratacao() == '3' ? 'selected' : '' ?>>Estágio</option>
                        <option value="4" <?= !empty($vaga) && $vaga->getRegimeContratacao() == '4' ? 'selected' : '' ?>>Jovem Aprendiz</option>
                </select>
                <label for="status" class="col-form-label">Regime de Contratação</label>
            </div>

             <!-- REGIME DE TRABALHO -->
            <div class="col-md-2 form-floating">
                <select class="form-control form-select" name="regimeTrabalho" id="regimeTrabalho">
                    <option value="0" required >Selecione</option>
                    <option value="1" <?= !empty($vaga) && $vaga->getRegimeTrabalho() == '1' ? 'selected' : '' ?>>Presencial</option>
                    <option value="2" <?= !empty($vaga) && $vaga->getRegimeTrabalho() == '2' ? 'selected' : '' ?>>Híbrido</option>
                    <option value="3" <?= !empty($vaga) && $vaga->getRegimeTrabalho() == '3' ? 'selected' : '' ?>>Remoto</option>
                </select>
                <label for="status" class="col-form-label">Regime de Trabalho</label>
            </div>

             <!-- NÍVEL DE SENIORIDADE -->
             <div class="col-md-2 form-floating">
                <select class="form-control form-select" name="nivelSenioridade" id="nivelSenioridade">
                    <option value="0" required >Selecione</option>
                    <option value="1" <?= !empty($vaga) && $vaga->getNivelSenioridade() == '1' ? 'selected' : '' ?>>Júnior</option>
                    <option value="2" <?= !empty($vaga) && $vaga->getNivelSenioridade() == '2' ? 'selected' : '' ?>>Pleno</option>
                    <option value="3" <?= !empty($vaga) && $vaga->getNivelSenioridade() == '3' ? 'selected' : '' ?>>Sênior</option>
                </select>
                <label for="status" class="col-form-label">Nível de Senioridade</label>
            </div>

             <!-- NÍVEL DE HIERARQUIA -->
             <div class="col-md-2 form-floating">
                <select class="form-control form-select" name="nivelHierarquia" id="nivelHierarquia">
                    <option value="0" required >Selecione</option>
                    <option value="1" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '1' ? 'selected' : '' ?>>Auxiliar/Assistente/Analista</option>
                    <option value="2" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '2' ? 'selected' : '' ?>>Coordenação/Supervisão</option>
                    <option value="3" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '3' ? 'selected' : '' ?>>Gerência</option>
                    <option value="4" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '4' ? 'selected' : '' ?>>Diretoria</option>
                    <option value="5" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '5' ? 'selected' : '' ?>>C-Level</option>
                </select>
                <label for="status" class="col-form-label">Nível de Senioridade</label>
            </div>
        </div>
        <div class="row gy-3 gy-md-4 overflow-hidden mt-4 mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Salvar</button>
                </div>
            </div>
        </div>
        <?php if(!empty($vaga)): ?>
            <table class="table">
                <thead>
                    <tr>Lista de Candidatos
                        <th scope="col">Nome</th>
                        <th scope="col">Email</th>
                        <th scope="col">Última Desistência</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($candidato_vagas as $candidato_vaga) : ?>
                    <tr>
                        <th><?=$candidato_vaga->getCandidato()->getNome()?></th>
                        <td><?=$candidato_vaga->getCandidato()->getEmail() ?></td>
                        <td><?=$candidato_vaga->getUltimaDesistencia()  ?></td>
                        <td><?=$candidato_vaga->getStatus()  ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </form>
</div>
