<?php /** @var Vaga $vaga */ ?>
<div class="container container-sm w-75">
    <form method="post" action="/vaga/salvar">
        <input type="hidden" name="vagaId" value="<?= isset($vaga) ? $vaga->getId() : '' ?>"/>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-8 form-floating">
                <input type="text" class="form-control" name="titulo" id="titulo" value="<?= isset($vaga) ? $vaga->getTitulo() : '' ?>">
                <label for="titulo" class="col-form-label">Título</label>
            </div>
            <div class="col-md-4 form-floating">
                <select class="form-control form-select" name="status" id="status">
                    <option value="1" <?= !empty($vaga) && $vaga->getStatus() == '1' ? 'selected' : '' ?>>Ativa</option>
                    <?php if (!empty($vaga)) : ?>
                        <option value="0" <?= $vaga->getStatus() == '0' ? 'selected' : '' ?>>Inativa</option>
                    <?php endif; ?>
                </select>
                <label for="status" class="col-form-label">Status</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-4 form-floating">
                <input type="text" class="form-control" name="email" id="email" value="<?= isset($vaga) ? $vaga->getEmail() : '' ?>">
                <label for="email" class="col-form-label">Email</label>
            </div>

            <div class="col-md-4">
                <div class="input-group">
                    <span class="input-group-text">R$</span>
                    <div class="form-floating">
                        <input type="number" class="form-control" name="salario" id="salario" value="<?= isset($vaga) ? $vaga->getSalario() : '' ?>" min="0">
                        <label for="salario" class="col-form-label">Salário</label>
                    </div>
                </div>
            </div>

            <div class="col-md-4 form-floating">
                <input type="number" class="form-control" name="cargaHoraria" id="cargaHoraria" value="<?= isset($vaga) ? $vaga->getCargaHoraria() : '' ?>" min="0">
                <label for="cargaHoraria" class="col-form-label">Carga horária</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-12 form-floating">
                <textarea class="form-control" cols="50" name="descricao" id="descricao" style="min-height: 100px;"><?= isset($vaga) ? $vaga->getDescricao() : '' ?></textarea>
                <label for="descricao" class="col-form-label">Descrição</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-12 form-floating">
                <textarea class="form-control" name="beneficios" id="beneficios" style="min-height: 100px;"><?= isset($vaga) ? $vaga->getBeneficios() : '' ?></textarea>
                <label for="beneficios" class="col-form-label">Benefícios</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <!-- REGIME DE CONTRATAÇÃO -->
            <div class="col-md-4 form-floating">
                <select class="form-control form-select" name="regimeContratacao" id="regimeContratacao" required>
                    <option value="">Selecione</option>
                    <option value="1" <?= !empty($vaga) && $vaga->getRegimeContratacao() == '1' ? 'selected' : '' ?>>CLT</option>
                    <option value="2" <?= !empty($vaga) && $vaga->getRegimeContratacao() == '2' ? 'selected' : '' ?>>PJ</option>
                    <option value="3" <?= !empty($vaga) && $vaga->getRegimeContratacao() == '3' ? 'selected' : '' ?>>Estágio</option>
                    <option value="4" <?= !empty($vaga) && $vaga->getRegimeContratacao() == '4' ? 'selected' : '' ?>>Jovem Aprendiz</option>
                </select>
                <label for="regimeContratacao" class="col-form-label">Regime de Contratação</label>
            </div>
            <!-- REGIME DE TRABALHO -->
            <div class="col-md-4 form-floating">
                <select class="form-control form-select" name="regimeTrabalho" id="regimeTrabalho" required>
                    <option value="">Selecione</option>
                    <option value="1" <?= !empty($vaga) && $vaga->getRegimeTrabalho() == '1' ? 'selected' : '' ?>>Presencial</option>
                    <option value="2" <?= !empty($vaga) && $vaga->getRegimeTrabalho() == '2' ? 'selected' : '' ?>>Híbrido</option>
                    <option value="3" <?= !empty($vaga) && $vaga->getRegimeTrabalho() == '3' ? 'selected' : '' ?>>Remoto</option>
                </select>
                <label for="regimeTrabalho" class="col-form-label">Regime de Trabalho</label>
            </div>
            <div class="col-md-4 form-floating">
                <select class="form-control form-select" name="filial" id="filial" required>
                    <option value="">Selecione a filial</option>
                    <?php
                    /** @var array<Filial> $filiais */
                    foreach ($filiais as $filial) : ?>
                        <option value="<?php echo $filial->getId() ?>" <?= !empty($vaga) && $vaga->getFilial()->getId() == $filial->getId() ? 'selected' : '' ?>><?php echo $filial->getNome() ?></option>
                    <?php endforeach; ?>
                </select>
                <label for="filial" class="col-form-label">Selecione a filial</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <!-- NÍVEL DE SENIORIDADE -->
            <div class="col-md-6 form-floating">
                <select class="form-control form-select" name="nivelSenioridade" id="nivelSenioridade" required>
                    <option value="">Selecione</option>
                    <option value="1" <?= !empty($vaga) && $vaga->getNivelSenioridade() == '1' ? 'selected' : '' ?>>Júnior</option>
                    <option value="2" <?= !empty($vaga) && $vaga->getNivelSenioridade() == '2' ? 'selected' : '' ?>>Pleno</option>
                    <option value="3" <?= !empty($vaga) && $vaga->getNivelSenioridade() == '3' ? 'selected' : '' ?>>Sênior</option>
                </select>
                <label for="nivelSenioridade" class="col-form-label">Nível de Senioridade</label>
            </div>

            <!-- NÍVEL DE HIERARQUIA -->
            <div class="col-md-6 form-floating">
                <select class="form-control form-select" name="nivelHierarquia" id="nivelHierarquia" required>
                    <option value="">Selecione</option>
                    <option value="1" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '1' ? 'selected' : '' ?>>Auxiliar/Assistente/Analista</option>
                    <option value="2" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '2' ? 'selected' : '' ?>>Coordenação/Supervisão</option>
                    <option value="3" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '3' ? 'selected' : '' ?>>Gerência</option>
                    <option value="4" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '4' ? 'selected' : '' ?>>Diretoria</option>
                    <option value="5" <?= !empty($vaga) && $vaga->getNivelHierarquico() == '5' ? 'selected' : '' ?>>C-Level</option>
                </select>
                <label for="nivelHierarquia" class="col-form-label">Nível hierárquico</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <label class="col-form-label">Habilidades</label>
            <?php /** @var array<Habilidade> $habilidades */
            foreach ($habilidades as $habilidade) : ?>
                <div class="col-3 mb-3" style="text-wrap: nowrap;" title="<?= $habilidade->getHabilidade() ?>">
                    <input type="checkbox" class="form-check-input" name="habilidade[]" id="habilidade_<?= $habilidade->getId() ?>" value="<?= $habilidade->getId() ?> "<?= !empty($vaga) && $vaga->temHabilidadeId($habilidade->getId()) ? 'checked' : '' ?>>
                    <label class="form-check-label ms-1 text-truncate" style="max-width: 80%;" for="habilidade_<?= $habilidade->getId() ?>"><?= $habilidade->getHabilidade() ?></label>
                </div>

            <?php endforeach; ?>

        </div>
        <div class="row gy-3 gy-md-4 overflow-hidden mt-4 mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-save"></i> Salvar
                    </button>
                </div>
            </div>
        </div>
    </form>

    <?php if (!empty($vaga)): ?>
        <hr>
        <table class="table table-bordered table-striped table-hover caption-top">
            <caption>Lista de Candidatos</caption>
            <thead>
            <tr>
                <th scope="col" class="minimal">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Última Desistência</th>
                <th scope="col">Status da Candidatura</th>
                <th scope="col" class="minimal">
                    <i class="fas fa-cog"></i>
                </th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var array<CandidatoVaga> $candidato_vagas */
            foreach ($candidato_vagas as $candidato_vaga) : ?>
                <tr>
                    <td><?= $candidato_vaga->getCandidato()->getId() ?></td>
                    <td><?= $candidato_vaga->getCandidato()->getNome() ?></td>
                    <td><?= $candidato_vaga->getCandidato()->getEmail() ?></td>
                    <td><?= $candidato_vaga->getUltimaDesistencia() ?></td>
                    <td><?= $candidato_vaga->getStatus(true) ?></td>
                    <td>
                        <?php if ($candidato_vaga->getStatus() !== CandidatoVagaStatusEnum::Desistencia->value && $candidato_vaga->getStatus() !== CandidatoVagaStatusEnum::Aprovado->value && $candidato_vaga->getStatus() !== CandidatoVagaStatusEnum::Reprovado->value) : ?>
                            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                                <a class="btn btn-success" href="/vaga/processaMudancaDeStatus?id=<?= $vaga->getId() ?>&candidatoId=<?= $candidato_vaga->getCandidato()->getId() ?>&resultado=1" title="Aprovar" role="button">
                                    <i class="fas fa-check-circle"></i>
                                </a>
                                <a class="btn btn-danger" href="/vaga/processaMudancaDeStatus?id=<?= $vaga->getId() ?>&candidatoId=<?= $candidato_vaga->getCandidato()->getId() ?>&resultado=0" title="Reprovar" role="button">
                                    <i class="fas fa-times-circle"></i>
                                </a>
                            </div>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>
