<table class="table table-bordered table-striped table-hover caption-top">
    <caption>Minhas vagas</caption>
    <?php foreach ($vagas as $vaga) : ?>
        <tr>
            <td><?= $vaga->getId() ?></td>
            <td><?= $vaga->getTitulo() ?></td>
            <td><?= $vaga->getStatus(true) ?></td>
            <td>
                <a class="btn btn-primary btn-sm" href="/vaga/editar?id=<?= $vaga->getId() ?>">Editar</a>
                <a class="btn btn-primary btn-sm" href="/vaga/excluir?id=<?= $vaga->getId() ?>">Excluir</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>