<?php
$filtros_badges = [];
foreach ($filtro_habilidades as $id_habilidade) {
    foreach ($habilidades as $habilidade) {
        if ($habilidade->getId() == $id_habilidade) {
            $filtros_badges[] = $habilidade->getHabilidade();
            break;
        }
    }
}
foreach ($filtro_empresas as $id_empresa) {
    foreach ($empresas as $empresa) {
        if ($empresa->getId() == $id_empresa) {
            $filtros_badges[] = $empresa->getNome();
            break;
        }
    }
}

$estados = EstadoEnum::forSelect();
foreach ($filtro_estados as $sigla_estado) {
    $filtros_badges[] = $estados[$sigla_estado];
}

$hierarquias = NivelHierarquicoEnum::forSelect();
foreach ($filtro_hierarquia as $indice) {
    $filtros_badges[] = $hierarquias[$indice];
}

$senioridades = NivelSenioridadeEnum::forSelect();
foreach ($filtro_senioridade as $indice) {
    $filtros_badges[] = $senioridades[$indice];
}

$regimes_contratacao = RegimeContratacaoEnum::forSelect();
foreach ($filtro_contratacao as $indice) {
    $filtros_badges[] = $regimes_contratacao[$indice];
}

$regimes_trabalho = RegimeTrabalhoEnum::forSelect();
foreach ($filtro_trabalho as $indice) {
    $filtros_badges[] = $regimes_trabalho[$indice];
}

$hasMinSalario = !empty($filtro_salarioDe) && $filtro_salarioDe != 0;
$hasMaxSalario = !empty($filtro_salarioAte) && $filtro_salarioAte != 1000000;

if ($hasMinSalario) {
    $filtros_badges[] = 'A partir de R$' . $filtro_salarioDe;
}

if ($hasMaxSalario) {
    $filtros_badges[] = 'Ate R$' . $filtro_salarioAte;
}

?>

<div class="hero min-h-[calc(100vh-64px)] bg-no-repeat bg-[url('https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')]">
    <div class="hero-overlay bg-opacity-70"></div>
    <div class="hero-content text-neutral-content text-center">
        <div class="max-w-xl">
            <h1 class="text-5xl font-quicksand font-bold">Encontre sua Vaga de Emprego</h1>
            <p class="py-6 text-lg">
                Confira gratuitamente as oportunidades de empregos nas empresas clientes da FoodFinder Jobs. Descubra oportunidades incríveis na indústria alimentícia.
            </p>
            <a class="btn btn-primary" href="#vagas">Explorar Vagas Agora</a>
        </div>
    </div>
</div>
<div class="bg-primary text-primary-content py-10 lg:py-16">
    <div class="flex flex-col lg:flex-row items-center justify-around max-w-screen-lg mx-auto px-4 gap-8">
        <h2 class="text-3xl font-bold font-quicksand text-center">Crie seu perfil para buscar milhares de vagas</h2>
        <div class="flex items-center">
            <a class="btn" href="#vagas">Explorar Vagas</a>
        </div>
    </div>
</div>
<div id="vagas" class="flex flex-col px-4 py-10 gap-10 justify-center items-center">
    <h2 class="text-3xl font-bold">Vagas</h2>
    <div class="grid md:grid-cols-5 xl:grid-cols-7 gap-4 max-w-screen-2xl w-full">
        <div class="flex-col gap-4 md:col-span-2 hidden md:flex">
            <h3 class="font-bold">Filtros</h3>
            <div>
                <?php require __DIR__ . '/filtros.phtml' ?>
            </div>
        </div>
        <div class="flex flex-col gap-4 md:col-span-2 md:hidden">
            <details class="collapse collapse-arrow bg-base-100">
                <summary class="collapse-title">
                    <h3 class="font-bold">Filtros</h3>
                </summary>
                <div class="collapse-content">
                    <?php require __DIR__ . '/filtros.phtml' ?>
                </div>
            </details>
        </div>
        <div class="flex flex-col gap-4 md:col-span-3 xl:col-span-5">
            <?php if (!empty($filtros_badges)) : ?>
                <div class="flex flex-wrap gap-2">
                    <span>Filtrado por:</span>
                    <?php foreach ($filtros_badges as $badge) : ?>
                        <div class="badge badge-primary badge-outline"><?= $badge ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif;
            if (empty($vagas)) : ?>
                <div role="alert" class="flex alert alert-warning">
                    <svg class="w-5 h-5" data-slot="icon" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path clip-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12Zm8.706-1.442c1.146-.573 2.437.463 2.126 1.706l-.709 2.836.042-.02a.75.75 0 0 1 .67 1.34l-.04.022c-1.147.573-2.438-.463-2.127-1.706l.71-2.836-.042.02a.75.75 0 1 1-.671-1.34l.041-.022ZM12 9a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z" fill-rule="evenodd"></path>
                    </svg>
                    <span>Nenhuma vaga encontrada.</span>
                </div>
            <?php endif; ?>
            <div class="grid xl:grid-cols-2 gap-x-4 gap-y-8 w-full">
                <?php
                /** @var array<Vaga> $vagas */
                foreach ($vagas as $vaga) :
                    echo $vaga->renderCardJob();
                endforeach; ?>
            </div>
        </div>
    </div>
</div>