<form action="/empresa/processaCadastrar" method="post">
    <div class="row gy-3 gy-md-4 overflow-hidden">
        <div class="col-12">
            <label for="nome" class="form-label">Nome da empresa
                <span class="text-danger">*</span></label>
            <input type="text" class="form-control" name="nome" id="nome" placeholder="Nome da Empresa" required>
        </div>
        <div class="col-12">
            <label for="cnpj" class="form-label">CNPJ
                <span class="text-danger">*</span></label>
            <input type="text" class="form-control" name="cnpj" id="cnpj" placeholder="CNPJ" required>
        </div>

        <div class="col-12">
            <label for="email" class="form-label">Email
                <span class="text-danger">*</span></label>
            <input type="email" class="form-control" name="email" id="email" placeholder="Informe um email válido" required>
        </div>

        <div class="col-12">
            <label for="descricao" class="form-label">Descrição
                <span class="text-danger">*</span></label>
            <textarea type="text" class="form-control" name="descricao" id="descricao" placeholder="Descrição" required></textarea>
        </div>
        <div class="col-12">
            <label for="logo" class="form-label">Logo
                <span class="text-danger">*</span></label>
            <input type="text" class="form-control" name="logo" id="logo" placeholder="adicione uma imagem" required>
        </div>
        <div class="col-12">
            <label for="endereco" class="form-label">Endereço
                <span class="text-danger">*</span></label>
            <input type="text" class="form-control" name="endereco" id="endereco" placeholder="Digite o Endereço Atual" required>
        </div>
        <hr>
        <h6>Dados do usuário</h6>
        <div class="col-12">
            <label for="usuarioCpf" class="form-label">CPF
                <span class="text-danger">*</span></label>
            <input type="text" class="form-control" name="usuarioCpf" id="usuarioCpf" placeholder="Informe o CPF do usuário" required>
        </div>
        <div class="col-12">
            <label for="usuarioNome" class="form-label">Nome
                <span class="text-danger">*</span></label>
            <input type="text" class="form-control" name="usuarioNome" id="usuarioNome" placeholder="Informe o nome do usuario" required>
        </div>
        <div class="col-12">
            <label for="usuarioEmail" class="form-label">Email
                <span class="text-danger">*</span></label>
            <input type="text" class="form-control" name="usuarioEmail" id="usuarioEmail" placeholder="Informe o e-mail do usuario" required>
        </div>
        <div class="col-12">
            <label for="usuarioSenha" class="form-label">Senha
                <span class="text-danger">*</span></label>
            <input type="password" class="form-control" name="usuarioSenha" id="usuarioSenha" value="" required>
        </div>
        <div class="col-12">
            <div class="d-grid">
                <button class="btn bsb-btn-xl btn-primary" type="submit">Cadastrar</button>
            </div>
        </div>
    </div>
</form>