<div class="mx-auto max-w-7xl border p-4 rounded-xl bg-white mt-10 mb-20">
    <?php echo FlashMessage::getMessage(); ?>

    <form action="/empresa/processaCadastrar" method="post" enctype="multipart/form-data">
        <div class="grid grid-cols-[1fr_auto_1fr]">
            <div>
                <div class="p-2 bg-slate-100 rounded-xl mb-5">
                    <h2 class="text-base font-semibold text-gray-900">Dados da empresa</h2>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-1/2">
                        <div class="label">
                            <span class="label-text">CNPJ</span>
                        </div>
                        <input type="text" name="cnpj" id="cnpj" maxlength="14" minlength="14" required placeholder="" class="input input-bordered w-full" oninput="this.value = this.value.replace(/[^0-9]/g, '');"/>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Nome da empresa</span>
                        </div>
                        <input type="text" name="nome" id="nome" required placeholder="" class="input input-bordered w-full"/>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Email da empresa</span>
                        </div>
                        <input type="email" name="email" id="email" required placeholder="" class="input input-bordered w-full"/>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Descrição da empresa</span>
                        </div>
                        <textarea name="descricao" id="descricao" required class="textarea textarea-bordered h-24 max-h-24 min-h-24"></textarea>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Logo da empresa</span>
                        </div>
                        <input type="file" name="logo" id="logo" required class="file-input file-input-bordered w-full"/>
                    </label>
                </div>
            </div>
            <div class="flex justify-center">
                <div class="divider  divider-horizontal w-1"></div>
            </div>
            <div>
                <div class="p-2 bg-slate-100 rounded-xl mb-5">
                    <h2 class="text-base font-semibold text-gray-900">Dados do usuário</h2>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-1/2">
                        <div class="label">
                            <span class="label-text">E-mail</span>
                        </div>
                        <input type="email" name="usuarioEmail" id="usuarioEmail" required placeholder="" class="input input-bordered w-full"/>
                        <div class="label">
                            <span class="label-text-alt">Esse e-mail será o login do usuário</span>
                        </div>
                    </label>
                    <label class="form-control w-1/2">
                        <div class="label">
                            <span class="label-text">Senha</span>
                        </div>
                        <input type="password" name="usuarioSenha" id="usuarioSenha" required minlength="8" placeholder="" class="input input-bordered w-full"/>
                        <div class="label">
                            <span class="label-text-alt">Mínimo 8 caracteres</span>
                        </div>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-1/2">
                        <div class="label">
                            <span class="label-text">CPF</span>
                        </div>
                        <input type="text" name="usuarioCpf" id="usuarioCpf" required placeholder="" minlength="11" maxlength="11" class="input input-bordered w-full" oninput="this.value = this.value.replace(/[^0-9]/g, '');"/>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Nome completo do usuário</span>
                        </div>
                        <input type="text" name="usuarioNome" id="usuarioNome" required class="input input-bordered w-full"/>
                    </label>
                </div>

                <div class="p-2 bg-slate-100 rounded-xl mb-5 mt-5">
                    <h2 class="text-base font-semibold text-gray-900">Dados da filial</h2>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-2/3">
                        <div class="label">
                            <span class="label-text">Nome/Apelido da filial</span>
                        </div>
                        <input type="text" name="filialNome" id="filialNome" required class="input input-bordered w-full"/>
                    </label>
                    <label class="form-control w-1/3">
                        <div class="label">
                            <span class="label-text">CEP</span>
                        </div>
                        <input type="text" name="filialCep" id="filialCep" minlength="8" maxlength="8" required class="input input-bordered w-full" oninput="this.value = this.value.replace(/[^0-9]/g, '');"/>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Logradouro</span>
                        </div>
                        <input type="text" name="filialLogradouro" id="filialLogradouro" class="input input-bordered w-full"/>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-1/3">
                        <div class="label">
                            <span class="label-text">Número</span>
                        </div>
                        <input type="text" name="filialNumero" id="filialNumero" class="input input-bordered w-full"/>
                    </label>
                    <label class="form-control w-2/3">
                        <div class="label">
                            <span class="label-text">Complemento</span>
                        </div>
                        <input type="text" name="filialComplemento" id="filialComplemento" class="input input-bordered w-full"/>
                    </label>
                </div>
                <div class="flex space-x-2">
                    <label class="form-control w-5/12">
                        <div class="label">
                            <span class="label-text">Bairro</span>
                        </div>
                        <input type="text" name="filialBairro" id="filialBairro" class="input input-bordered w-full"/>
                    </label>
                    <label class="form-control w-5/12">
                        <div class="label">
                            <span class="label-text">Cidade</span>
                        </div>
                        <input type="text" name="filialCidade" id="filialCidade" required class="input input-bordered w-full"/>
                    </label>
                    <label class="form-control w-2/12">
                        <div class="label">
                            <span class="label-text">Estado</span>
                        </div>
                        <select class="select select-bordered w-full" name="filialEstado" id="filialEstado" required>
                            <option value="" disabled selected>-</option>
                            <?php foreach (EstadoEnum::forSelect() as $indice => $valor): ?>
                                <option value="<?= $indice ?>" <?= !empty($filial) && $filial->getEstado() == $indice ? 'selected' : '' ?>><?= $valor ?></option>
                            <?php endforeach; ?>
                        </select>
                    </label>
                </div>

            </div>
        </div>
        <div class="mt-10 mb-10 flex items-center justify-end">
            <button class="btn btn-primary btn-block" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.59 14.37a6 6 0 0 1-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 0 0 6.16-12.12A14.98 14.98 0 0 0 9.631 8.41m5.96 5.96a14.926 14.926 0 0 1-5.841 2.58m-.119-8.54a6 6 0 0 0-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 0 0-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 0 1-2.448-2.448 14.9 14.9 0 0 1 .06-.312m-2.24 2.39a4.493 4.493 0 0 0-1.757 4.306 4.493 4.493 0 0 0 4.306-1.758M16.5 9a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z"/>
                </svg>
                Cadastrar minha empresa
            </button>
        </div>

        <div class="divider"></div>
        <div class="flex items-center justify-center font-semibold mt-5">
            Já possui cadastro?
        </div>
        <div class="flex items-center justify-center mt-2">
            <a href="/autenticacao/?tab=2" class="btn btn-neutral font-bold btn-block">Efetue seu login!</a>
        </div>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        let campo = document.querySelector("#filialCep");
        campo.addEventListener('blur', function () {
            if (campo.value.trim() == '') {
                return;
            }

            // let url = 'https://brasilapi.com.br/api/cep/v1/' + campo.value;
            let url = '/api/cep/?cep=' + campo.value;
            fetch(url)
                .then(response => {
                    if (response.status !== 200) {
                        throw new Error('Erro lalallaa')
                    }
                    return response.json()
                })
                .then(data => {
                    document.querySelector("#filialLogradouro").value = data.street;
                    document.querySelector("#filialBairro").value = data.neighborhood;
                    document.querySelector("#filialCidade").value = data.city;
                    document.querySelector("#filialEstado").value = data.state;

                })
                .catch(error => {
                    alert('CEP não encontrado');
                    campo.value = '';
                    document.querySelector("#filialLogradouro").value = '';
                    document.querySelector("#filialBairro").value = '';
                    document.querySelector("#filialCidade").value = '';
                    document.querySelector("#filialEstado").value = '';
                })
        });

        let campoCnpj = document.querySelector("#cnpj")
        campoCnpj.addEventListener('blur', function () {
            // let url = 'https://brasilapi.com.br/api/cnpj/v1/' + campoCnpj.value
            let url = '/api/cnpj/?cnpj=' + campoCnpj.value;
            fetch(url)
                .then(response => {
                    if (response.status !== 200) {
                        throw new Error('')
                    }
                    return response.json()
                })
                .then(data => {
                    document.querySelector('#nome').value = data.nome_fantasia
                    document.querySelector('#filialNome').value = data.nome_fantasia + ' - Matriz'
                })
                .catch(error => {
                    document.querySelector('#nome').value = ''
                    document.querySelector('#filialNome').value = 'Matriz'
                })
        })
    });
</script>
