<?php
    /** @var Empresa $empresa */
?>
<div class="mx-auto max-w-4xl border p-4 m-14 rounded-xl bg-white">
    <form method="post" action="/empresa/editar" enctype="multipart/form-data">
        <div class="p-2 bg-slate-100 rounded-xl">
            <h2 class="text-base font-semibold text-gray-900">Dados da empresa</h2>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-2/3">
                <div class="label">
                    <span class="label-text">Nome</span>
                </div>
                <input type="hidden" readonly required name="nome" id="nome" value="<?= $empresa->getNome() ?>"/>
                <input type="text" disabled class="input input-bordered w-full" value="<?= $empresa->getNome() ?>"/>
            </label>
            <label class="form-control w-1/3">
                <div class="label">
                    <span class="label-text">CNPJ</span>
                </div>
                <input type="hidden" readonly required name="cnpj" id="cnpj" value="<?= $empresa->getCNPJ() ?>"/>
                <input type="text" disabled class="input input-bordered w-full" value="<?= $empresa->getCNPJ() ?>"/>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">E-mail</span>
                </div>
                <input type="text" required name="email" id="email" class="input input-bordered w-full" value="<?= $empresa->getEmail() ?>"/>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Descrição</span>
                </div>
                <textarea name="descricao" id="descricao" required class="textarea textarea-bordered h-24 max-h-24 min-h-24"><?= $empresa->getDescricao() ?></textarea>
            </label>
        </div>
        <div class="flex space-x-2 items-center">

            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Logo da empresa</span>
                </div>
                <input type="file" name="logo" id="logo" class="file-input file-input-bordered w-full"/>
                <div class="label">
                    <span class="label-text-alt text-neutral">Deixe este campo em branco se não quiser alterar o logo atual.</span>
                </div>
            </label>
            <div class="h-14 w-14">
                <img width="56" height="56" class="object-cover w-full h-full rounded-full mask mask-squircle object-cover" src="<?= $empresa->getLogo() ?>"/>
            </div>
        </div>

        <div class="mt-6 flex items-center justify-end">
            <button type="submit" class="btn btn-wide rounded-md btn-success text-white hover:bg-green-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                </svg>
                Salvar
            </button>
        </div>
    </form>

    <div class="divider"></div>
    <div class="mt-6 flex items-center justify-end">
        <a href="/empresa/exclusao" class="btn btn-block rounded-md btn-error text-white">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/>
            </svg>
            Excluir conta
        </a>
    </div>
</div>
