<div class="mx-auto max-w-4xl border p-4 m-14 rounded-xl bg-white">
    <form method="post" action="/empresa/processaEditar" enctype="multipart/form-data">
        <div class="p-2 bg-slate-100 rounded-xl">
            <h2 class="text-base font-semibold text-gray-900">Dados da empresa</h2>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-2/3">
                <div class="label">
                    <span class="label-text">Nome</span>
                </div>
                <input type="hidden" readonly required name="nome" id="nome" value="<?= $_SESSION['usuario']->getEmpresa()->getNome() ?>"/>
                <input type="text" disabled class="input input-bordered w-full" value="<?= $_SESSION['usuario']->getEmpresa()->getNome() ?>"/>
            </label>
            <label class="form-control w-1/3">
                <div class="label">
                    <span class="label-text">CNPJ</span>
                </div>
                <input type="hidden" readonly required name="cnpj" id="cnpj" value="<?= $_SESSION['usuario']->getEmpresa()->getCNPJ() ?>"/>
                <input type="text" disabled class="input input-bordered w-full" value="<?= $_SESSION['usuario']->getEmpresa()->getCNPJ() ?>"/>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">E-mail</span>
                </div>
                <input type="text" required name="email" id="email" class="input input-bordered w-full" value="<?= $_SESSION['usuario']->getEmpresa()->getEmail() ?>"/>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Descrição</span>
                </div>
                <textarea name="descricao" id="descricao" required class="textarea textarea-bordered h-24 max-h-24 min-h-24"><?= $_SESSION['usuario']->getEmpresa()->getDescricao() ?></textarea>
            </label>
        </div>
        <div class="flex space-x-2 items-center">

            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Logo da empresa</span>
                </div>
                <input type="file" name="logo" id="logo" required class="file-input file-input-bordered w-full"/>
                <div class="label">
                    <span class="label-text-alt text-neutral">Deixe este campo em branco se não quiser alterar o logo atual.</span>
                </div>
            </label>
            <div class="h-14 w-14">
                <img width="56" height="56" class="object-cover w-full h-full rounded-full mask mask-squircle object-cover" src="<?= $_SESSION['usuario']->getEmpresa()->getLogo() ?>"/>
            </div>
        </div>

        <div class="mt-6 flex items-center justify-end">
            <button type="submit" class="btn btn-wide rounded-md btn-success text-white hover:bg-green-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Salvar</button>
        </div>
    </form>
</div>
