<div class="container container-sm w-75">
    <form method="post" action="/empresa/processaEditar" enctype="multipart/form-data">
        <div class="row gy-3 gy-md-4 overflow-hidden mb-2">
            <div class="col-md-6 form-floating">
                <input type="text" readonly class="form-control form-control-plaintext text-muted" name="nome" id="nome" required value="<?= $_SESSION['usuario']->getEmpresa()->getNome() ?>">
                <label for="nome" class="form-label">Nome
                    <span class="text-danger">*</span></label>
            </div>
            <div class="col-md-6 form-floating">
                <input type="text" readonly class="form-control form-control-plaintext text-muted" name="cnpj" id="cnpj" required value="<?= $_SESSION['usuario']->getEmpresa()->getCNPJ() ?>">
                <label for="cnpj" class="form-label">CNPJ
                    <span class="text-danger">*</span></label>
            </div>
        </div>
        <div class="row gy-3 gy-md-4 overflow-hidden mb-2">
            <div class="col-md-12 form-floating">

                <input type="email" class="form-control" name="email" id="email" required value="<?= $_SESSION['usuario']->getEmpresa()->getEmail() ?>">
                <label for="email" class="form-label">E-mail
                    <span class="text-danger">*</span></label>
            </div>
        </div>
        <div class="row gy-3 gy-md-4 overflow-hidden mb-2">
            <div class="col-md-12 form-floating">
                <textarea class="form-control" name="descricao" id="descricao" required><?= $_SESSION['usuario']->getEmpresa()->getDescricao() ?></textarea>
                <label for="descricao" class="form-label ">Descrição
                    <span class="text-danger">*</span></label>
            </div>
        </div>
        <div class="row gy-3 gy-md-4 overflow-hidden mb-2">
            <div class="col-md-12 form-floating">
                <input type="file" class="form-control" name="logo" id="logo" required>
                <label for="logo" class="form-label">Logo
                    <span class="text-danger">*</span></label>
            </div>
        </div>
        <div class="row gy-3 gy-md-4 overflow-hidden mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-save"></i> Salvar
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>