<?php
/**
 * @var Empresa $empresa
 * @var array $dados
 * @var array<Depoimento> $depoimentos
 * @var array<Vaga> $vagas
 * @var array<Candidato> $candidatos
 * */
?>
<div id="vagas" class="flex flex-col px-4 py-10 gap-10 justify-center items-center">
    <h1 class="font-bold"><?= $empresa->getNome(); ?></h1>
    <div class="stats shadow">
        <div class="stat">
            <div class="stat-title">Vagas abertas</div>
            <div class="stat-value"><?=$dados['vagas_abertas']?></div>
            <div class="stat-desc">até o momento</div>
        </div>
        <div class="stat">
            <div class="stat-title">Vagas fechadas</div>
            <div class="stat-value"><?=$dados['vagas_fechadas']?></div>
            <div class="stat-desc"><?=floor($dados['vagas_fechadas']/$dados['vagas_abertas']*100)?>% das vagas abertas</div>
        </div>
        <div class="stat">
            <div class="stat-title">Média de tempo</div>
            <div class="stat-value"><?=rand(1,20)?> dias</div>
            <div class="stat-desc">por processo seletivo</div>
        </div>
        <div class="stat">
            <div class="stat-title">Empresa</div>
            <div class="stat-value"><?=round($dados['media_avaliacao'])?></div>
            <div class="stat-desc">estrela(s)</div>
            <div class="stat-figure text-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="inline-block h-8 w-8 stroke-current text-orange-400">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 0 1 1.04 0l2.125 5.111a.563.563 0 0 0 .475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 0 0-.182.557l1.285 5.385a.562.562 0 0 1-.84.61l-4.725-2.885a.562.562 0 0 0-.586 0L6.982 20.54a.562.562 0 0 1-.84-.61l1.285-5.386a.562.562 0 0 0-.182-.557l-4.204-3.602a.562.562 0 0 1 .321-.988l5.518-.442a.563.563 0 0 0 .475-.345L11.48 3.5Z"/>
                </svg>
            </div>

        </div>
        <div class="stat">
            <div class="stat-title">Contratou</div>
            <div class="stat-value"><?=round($dados['contratacoes'])?></div>
            <div class="stat-desc">candidato(s)</div>
            <div class="stat-figure text-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block h-8 w-8 stroke-current text-orange-400">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 14.15v4.25c0 1.094-.787 2.036-1.872 2.18-2.087.277-4.216.42-6.378.42s-4.291-.143-6.378-.42c-1.085-.144-1.872-1.086-1.872-2.18v-4.25m16.5 0a2.18 2.18 0 0 0 .75-1.661V8.706c0-1.081-.768-2.015-1.837-2.175a48.114 48.114 0 0 0-3.413-.387m4.5 8.006c-.194.165-.42.295-.673.38A23.978 23.978 0 0 1 12 15.75c-2.648 0-5.195-.429-7.577-1.22a2.016 2.016 0 0 1-.673-.38m0 0A2.18 2.18 0 0 1 3 12.489V8.706c0-1.081.768-2.015 1.837-2.175a48.111 48.111 0 0 1 3.413-.387m7.5 0V5.25A2.25 2.25 0 0 0 13.5 3h-3a2.25 2.25 0 0 0-2.25 2.25v.894m7.5 0a48.667 48.667 0 0 0-7.5 0M12 12.75h.008v.008H12v-.008Z"/>
                </svg>
            </div>
        </div>
    </div>
    <?php if (!empty($depoimentos)): ?>
        <h1 class="font-bold">O que dizem sobre <?= $empresa->getNome(); ?></h1>
        <div class="carousel w-2/5 h-[250px]">
            <?php
            $anterior = count($depoimentos) - 1;
            $proximo = 1;
            foreach ($depoimentos as $atual => $depoimento):
                $candidato = $candidatos[$atual];
                ?>
                <div id="slide<?= $atual ?>" class="carousel-item relative w-full justify-center">
                    <div class="p-4 rounded-box w-full">
                        <div class="flex justify-center">
                            <div class="rating justify-center">
                                <input readonly disabled type="radio" name="rating<?= $depoimento->getId() ?>" value="1" class="mask mask-star bg-orange-400" <?= $depoimento->getAvaliacao() == 1 ? 'checked' : "" ?>/>
                                <input readonly disabled type="radio" name="rating<?= $depoimento->getId() ?>" value="2" class="mask mask-star bg-orange-400" <?= $depoimento->getAvaliacao() == 2 ? 'checked' : "" ?>/>
                                <input readonly disabled type="radio" name="rating<?= $depoimento->getId() ?>" value="3" class="mask mask-star bg-orange-400" <?= $depoimento->getAvaliacao() == 3 ? 'checked' : "" ?>/>
                                <input readonly disabled type="radio" name="rating<?= $depoimento->getId() ?>" value="4" class="mask mask-star bg-orange-400" <?= $depoimento->getAvaliacao() == 4 ? 'checked' : "" ?>/>
                                <input readonly disabled type="radio" name="rating<?= $depoimento->getId() ?>" value="5" class="mask mask-star bg-orange-400" <?= $depoimento->getAvaliacao() == 5 ? 'checked' : "" ?>/>
                            </div>
                        </div>
                        <div class="flex justify-center items-center h-3/4">
                            <div class="chat chat-start flex justify-center w-3/5">
                                <div class="chat-image avatar">
                                    <div class="avatar placeholder">
                                        <div class="bg-neutral/90 text-neutral-content w-12 rounded-full">
                                        <span class="text-1xl"><?= join('', array_map(function ($name) {
                                                return $name[0];
                                            }, explode(' ', $candidato->getNome()))) ?></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-bubble whitespace-nowrap"><?= $depoimento->getDepoimento() ?></div>
                            </div>
                        </div>
                        <div class="flex justify-center text-xs">
                            <?= join("/", [$atual + 1, count($depoimentos)]) ?>
                        </div>
                        <div class="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
                            <a href="#slide<?= $anterior ?>" class="btn btn-circle btn-neutral">❮</a>
                            <a href="#slide<?= $proximo ?>" class="btn btn-circle btn-neutral">❯</a>
                        </div>
                    </div>
                </div>
                <?php
                $anterior++;
                $proximo++;

                if ($anterior >= count($depoimentos)) {
                    $anterior = 0;
                }

                if ($proximo >= count($depoimentos)) {
                    $proximo = 0;
                }
            endforeach;
            ?>
        </div>
    <?php endif; ?>
    <?php if (!empty($vagas)): ?>
        <h1 class="font-bold">Confira todas as vagas de <?= $empresa->getNome(); ?></h1>
        <div class="carousel w-2/5 h-[250px]">
            <?php foreach ($vagas as $atual => $vaga): ?>
                <div id="vaga<?= $vaga->getId() ?>" class="carousel-item w-full">
                    <?= $vaga->cardFormatado() ?>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="flex w-full justify-center gap-2 py-2">
            <?php foreach ($vagas as $atual => $vaga): ?>
                <a href="#vaga<?= $vaga->getId() ?>" class="btn btn-xs bg-white"><?= $atual + 1 ?></a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
