<!DOCTYPE html>
<html lang="pt-BR" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=TITLE?></title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="/assets/css/google/fonts/familyInter.css" rel="stylesheet">
    <link href="/assets/css/daisyui/4.12.10/full.css" rel="stylesheet" type="text/css"/>
    <script src="/assets/js/tailwindcss/plugins/typography.js"></script>
    <script>
        tailwind.config = {
            theme: {
                fontFamily: {
                    'body': ['Inter', 'sans-serif'],
                    'title': ['Quicksand', 'sans-serif'],
                }
            },
            darkMode: ['class', '[data-theme="dark"]']
        }
    </script>
    <style type="text/tailwindcss">
        html {
            scroll-behavior: smooth;
        }

        .btn {
            font-family: 'Quicksand', sans-serif;
        }

        @layer base {
            h1 {
                @apply text-3xl font-title;
            }

            h2 {
                @apply text-2xl font-title;
            }

            h3 {
                @apply text-xl font-title;
            }

            h4 {
                @apply text-lg font-title;
            }

            h5 {
                @apply text-base font-title;
            }

            h6 {
                @apply text-sm font-title;
            }

            p {
                @apply text-base;
            }

            span {
                @apply text-sm font-medium;
            }
        }
    </style>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var theme = document.cookie.replace(/(?:(?:^|.*;\s*)theme\s*\=\s*([^;]*).*$)|^.*$/, "$1");
            // document.body.setAttribute('data-theme', theme || 'light');
            document.getElementById('switch-theme').checked = theme === 'dark';
        });
    </script>

</head>

<body data-theme="<?= $_COOKIE['theme'] ?? 'light'; ?>" class="flex flex-col min-h-screen font-body bg-base-200 text-base-content">
<header class="border-b border-b-base-300 font-title">
    <div class="navbar max-w-screen-lg mx-auto justify-between">
        <div class="navbar-start w-auto">
            <div class="dropdown">
                <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16"/>
                    </svg>
                </div>
                <ul tabindex="0" class="menu menu-md dropdown-content bg-base-200 rounded-box z-[1] mt-3 w-[200px] p-2 shadow">
                    <li>
                        <a href="/">Painel de vagas</a>
                    </li>
                    <li>
                        <a href="/autenticacao">Área da empresa</a>
                    </li>
                    <li>
                        <a href="/candidato/login">Área do candidato</a>
                    </li>
                    <li>
                        <label class="swap swap-rotate">
                            <input type="checkbox" name="switch-theme" id="switch-theme" onchange="toggleTheme()" <?php echo (isset($_COOKIE['theme']) && $_COOKIE['theme'] === 'dark') ? 'checked' : ''; ?> />

                            <!-- sun icon -->
                            <svg class="swap-on h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"/>
                            </svg>

                            <!-- moon icon -->
                            <svg class="swap-off h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"/>
                            </svg>
                        </label>
                    </li>
                </ul>
            </div>
            <a class="btn btn-ghost flex gap-2 text-xl" href="/">
                <svg width="30" height="30" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current">
                    <path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path>
                </svg>
                FoodFinder Jobs
            </a>
        </div>
        <div class="navbar-end w-auto hidden lg:flex">
            <ul class="menu menu-horizontal px-1 gap-2">
                <li>
                    <a class="btn btn-ghost" href="/">Painel de vagas</a>
                </li>
                <li>
                    <a class="btn btn-ghost" href="/autenticacao">Área da empresa</a>
                </li>
                <li>
                    <a class="btn btn-primary" href="/candidato/login">Área do candidato</a>
                </li>
                <li class="flex justify-center">
                    <label class="swap swap-rotate">
                        <input type="checkbox" name="switch-theme" id="switch-theme" onchange="toggleTheme()" <?php echo (isset($_COOKIE['theme']) && $_COOKIE['theme'] === 'dark') ? 'checked' : ''; ?> />

                        <!-- sun icon -->
                        <svg class="swap-on h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"/>
                        </svg>

                        <!-- moon icon -->
                        <svg class="swap-off h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"/>
                        </svg>
                    </label>
                </li>
            </ul>
        </div>
    </div>
</header>
<main>
    <?php if (!isset($_GET['id'])): ?>
    <div class="hero min-h-[calc(50vh-64px)] bg-no-repeat bg-[url('/assets/images/photo-1521737711867-e3b97375f902.avif')]">
        <div class="hero-overlay bg-opacity-70"></div>
        <div class="hero-content text-neutral-content text-center">
            <div class="max-w-xl">
                <h1 class="text-5xl font-quicksand font-bold">Encontre sua<br>Vaga de Emprego</h1>
                <p class="py-6 text-lg">
                    Confira gratuitamente as oportunidades de empregos nos parceiros da FoodFinder Jobs.<br>Descubra oportunidades incríveis para acelerar sua carreira.
                </p>
                <a class="btn btn-primary" href="#vagas">Explorar Agora</a>
            </div>
        </div>
    </div>
    <div class="bg-primary text-primary-content py-8">
        <div class="flex flex-col lg:flex-row items-center justify-around max-w-screen-lg mx-auto px-4 gap-8">
            <h2 class="text-3xl font-bold font-quicksand text-center">Crie seu perfil para buscar milhares de vagas</h2>
            <div class="flex items-center">
                <a class="btn" href="/candidato/cadastrar">Quero me cadastrar!</a>
            </div>
        </div>
    </div>
<?php endif; ?>