<form method="post" action="/usuario/salvar">
    <input type="hidden" name="usuarioId" value="<?= isset($usuarioEdicao) ? $usuarioEdicao->getId() : '' ?>"/>
    <div class="row g-3 align-items-center mb-2">
        <label for="cpf" class="col-form-label col-md-2">CPF</label>
        <div class="col-md-10">
            <input type="text" class="form-control" name="cpf" id="cpf" value="<?= isset($usuarioEdicao) ? $usuarioEdicao->getCpf() : '' ?>">
        </div>
    </div>
    <div class="row g-3 align-items-center mb-2">
        <label for="nome" class="col-form-label col-md-2">Nome</label>
        <div class="col-md-10">
            <input type="text" class="form-control" name="nome" id="nome" value="<?= isset($usuarioEdicao) ? $usuarioEdicao->getNome() : '' ?>">
        </div>
    </div>
    <div class="row g-3 align-items-center mb-2">
        <label for="email" class="col-form-label col-md-2">Email</label>
        <div class="col-md-10">
            <input type="text" class="form-control" name="email" id="email" value="<?= isset($usuarioEdicao) ? $usuarioEdicao->getEmail() : '' ?>">
        </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-md-12 d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-end">
            <button class="btn btn-primary">Salvar</button>
        </div>
    </div>
</form>