<dialog id="modal" class="modal modal-lg" onclick="close_modal(event, 'modal')">
    <div class="modal-box max-w-3xl" onclick="event.stopPropagation()">
        <form method="post" action="/usuario/salvar">
            <input type="hidden" name="usuarioId" id="usuarioId" value="<?= isset($usuarioEdicao) ? $usuarioEdicao->getId() : '' ?>"/>
            <div class="flex space-x-2">
                <label class="form-control w-2/3">
                    <div class="label">
                        <span class="label-text">Nome completo</span>
                    </div>
                    <input type="text" name="nome" id="nome" required value="<?= isset($usuarioEdicao) ? $usuarioEdicao->getNome() : '' ?>" class="input input-bordered w-full"/>
                </label>

                <label class="form-control w-1/3">
                    <div class="label">
                        <span class="label-text">CPF</span>
                    </div>
                    <input type="text" name="cpf" id="cpf" required value="<?= isset($usuarioEdicao) ? $usuarioEdicao->getCpf() : '' ?>" minlength="11" maxlength="11" class="input input-bordered w-full" oninput="this.value = this.value.replace(/[^0-9]/g, '');"/>
                    <div class="label p-0 mt-1">
                        <span class="label-text-alt">Exatos 11 caracteres</span>
                    </div>
                    <div class="label p-0">
                        <span class="label-text-alt">Somente números</span>
                    </div>
                </label>
            </div>
            <div class="flex space-x-2">
                <label class="form-control w-full">
                    <div class="label">
                        <span class="label-text">E-mail</span>
                    </div>
                    <input type="email" name="email" id="email" required value="<?= isset($usuarioEdicao) ? $usuarioEdicao->getEmail() : '' ?>" class="input input-bordered w-full"/>
                    <div class="label">
                        <span class="label-text-alt">Esse e-mail será o login do usuário</span>
                    </div>
                </label>
            </div>
            <div class="mt-6 flex items-center justify-between space-x-2">
                <button class="btn btn-neutral" onclick="close_modal(event, 'modal')">Cancelar</button>
                <button class="btn btn-success btn-wide" type="submit">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                    </svg>
                    Salvar
                </button>
            </div>
        </form>
    </div>
</dialog>

<div class="overflow-x-auto flex justify-center w-full mb-10 mt-5">
    <table class="border-collapse table-sm table-zebra border-collapse dark:border-slate-500 bg-white dark:bg-slate-800 text-sm shadow-sm w-3/5">
        <caption class="text-slate-500 dark:text-slate-400 pb-4 text-md caption-top">
            <div class="flex">
                <div class="w-full flex items-center justify-start">
                    <h2 class="shadow">Nossos usuários</h2>
                </div>
                <div class="flex justify-end">
                    <button class="btn btn-success btn-sm text-white" id="cadastrar" onclick="modal.showModal()">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                        </svg>
                        Cadastrar
                    </button>
                </div>
            </div>
        </caption>
        <thead class="bg-slate-50 dark:bg-slate-700">
        <tr>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200 whitespace-nowrap w-0">#</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200 whitespace-nowrap w-full">Nome</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200 whitespace-nowrap w-full">CPF</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200 whitespace-nowrap w-full">E-mail</th>
            <th class="border border-slate-300 dark:border-slate-600 font-semibold text-slate-900 dark:text-slate-200 whitespace-nowrap w-0">
                <div class="flex justify-center items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
                        <path fill-rule="evenodd" d="M6.955 1.45A.5.5 0 0 1 7.452 1h1.096a.5.5 0 0 1 .497.45l.17 1.699c.484.12.94.312 1.356.562l1.321-1.081a.5.5 0 0 1 .67.033l.774.775a.5.5 0 0 1 .034.67l-1.08 1.32c.25.417.44.873.561 1.357l1.699.17a.5.5 0 0 1 .45.497v1.096a.5.5 0 0 1-.45.497l-1.699.17c-.12.484-.312.94-.562 1.356l1.082 1.322a.5.5 0 0 1-.034.67l-.774.774a.5.5 0 0 1-.67.033l-1.322-1.08c-.416.25-.872.44-1.356.561l-.17 1.699a.5.5 0 0 1-.497.45H7.452a.5.5 0 0 1-.497-.45l-.17-1.699a4.973 4.973 0 0 1-1.356-.562L4.108 13.37a.5.5 0 0 1-.67-.033l-.774-.775a.5.5 0 0 1-.034-.67l1.08-1.32a4.971 4.971 0 0 1-.561-1.357l-1.699-.17A.5.5 0 0 1 1 8.548V7.452a.5.5 0 0 1 .45-.497l1.699-.17c.12-.484.312-.94.562-1.356L2.629 4.107a.5.5 0 0 1 .034-.67l.774-.774a.5.5 0 0 1 .67-.033L5.43 3.71a4.97 4.97 0 0 1 1.356-.561l.17-1.699ZM6 8c0 .538.212 1.026.558 1.385l.057.057a2 2 0 0 0 2.828-2.828l-.058-.056A2 2 0 0 0 6 8Z" clip-rule="evenodd"/>
                    </svg>
                </div>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        /** @var array<Usuario> $usuarios */
        foreach ($usuarios as $usuarioAtual) : ?>
            <tr class="hover">
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400"><?= $usuarioAtual->getId(); ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400 whitespace-nowrap"><?= $usuarioAtual->getNome(); ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400 whitespace-nowrap"><?= $usuarioAtual->getCpf(); ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400 whitespace-nowrap"><?= $usuarioAtual->getEmail(); ?></td>
                <td class="border border-slate-300 dark:border-slate-700 text-slate-500 dark:text-slate-400">
                    <div class="flex justify-center space-x-1">
                        <button class=" btn btn-xs h-8 w-8 border btn-square border-accent-content/15" name="editar" data-usuarioid="<?= $usuarioAtual->getId() ?>" title="Editar">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10"/>
                            </svg>
                        </button>
                        <?php if ($usuarioAtual->getId() !== $_SESSION['usuario']->getId()) : ?>
                            <a class="btn btn-xs h-8 w-8 border btn-square border-accent-content/15 text-error" href="/usuario/excluir?id=<?= $usuarioAtual->getId() ?>" title="Excluir">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/>
                                </svg>
                            </a>
                        <?php else: ?>
                            <button class="btn btn-xs h-8 w-8 border btn-square border-accent-content/15 text-error" disabled title="Impossível deletar seu próprio usuário">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/>
                                </svg>
                            </button>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        let botoes = document.querySelectorAll("button[name='editar']")

        botoes.forEach(function (item) {
            item.addEventListener('click', function (event) {
                fetch('/usuario/detalhes', {
                    method: 'POST',
                    headers: {
                        'Content-type': 'application/json'
                    },
                    body: JSON.stringify({
                        id: item.getAttribute('data-usuarioid')
                    }),
                })
                    .then(response => response.json())
                    .then(data => {
                        document.getElementById('usuarioId').value = data.id
                        document.getElementById("nome").value = data.nome
                        document.getElementById("cpf").value = data.cpf
                        document.getElementById("email").value = data.email
                        modal.showModal()
                    })
            })
        })

        document.getElementById('cadastrar').addEventListener('click', function () {
            document.getElementById('usuarioId').value = ""
            document.getElementById("nome").value = ""
            document.getElementById("email").value = ""
            document.getElementById("cpf").value = ""
        });
    });
</script>