<div class="container container-sm w-50">
    <form method="post" action="/usuario/salvar">
        <input type="hidden" name="usuarioId" value="<?= isset($usuarioAlteracao) ? $usuarioAlteracao->getId() : '' ?>"/>
        <div class="row g-3 align-items-center mb-2">
            <label for="senhaAtual" class="col-form-label text-end align-content-end col-md-2">Digite a senha atual <span class="text-danger">*</span></label>
            <div class="col-md-10">
            <input type="password" class="form-control" name="senhaAtual" id="senhaAtual" minlength="8" required placeholder="SenhaAtual">
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <label for="novaSenha" class="col-form-label text-end align-content-end col-md-2">Digite a nova senha <span class="text-danger">*</span></label></label>
            <div class="col-md-3">
            <input type="password" class="form-control" name="novaSenha" id="novaSenha" minlength="8" required placeholder="NovaSenha">
            </div>
        </div>

        <div class="row gy-3 gy-md-4 overflow-hidden mt-4 mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>