<div class="container container-sm w-25">
    <form method="post" action="/usuario/salvarSenha">
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-12 form-floating">
                <input type="password" class="form-control" name="senha" id="senha" minlength="8" required>
                <label for="senha" class="col-form-label ">Digite a nova senha
                    <span class="text-danger">*</span></label></label>
            </div>
        </div>

        <div class="row gy-3 gy-md-4 overflow-hidden mt-4 mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-save"></i> Salvar
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>