<div class="container container-sm w-50">
    <form method="post" action="/habilidade/processaCadastrar">
        <input type="hidden" name="id" value="<?=isset($habilidade) ? $habilidade->getId() : ''?>"/>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-10">
                <label for="nome" class="col-form-label text-end align-content-center col-md-2">Habilidades
                    <input type="text" name="habilidade" value="<?= isset($habilidade) ? $habilidade->getHabilidade() : '' ?>">
                </label>
        </div>


        <div class="row gy-3 gy-md-4 overflow-hidden mt-4 mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>