<div class="container container-md w-50">
    <form method="post" action="/habilidade/salvar">
        <div class="row g-3 align-items-center mb-2">
            <label for="categoria" class="form-label">Categoria *</label>
            <select class="form-control form-select" name="categoria" id="categoria" required>
                <option value="" disabled selected>Selecione</option>
                <?php foreach ($categorias as $categoria) : ?>
                    <option value=<?=$categoria->getId()?> <?= isset($habilidade) && $habilidade->getCategoria()->getId() === $categoria->getId() ? 'selected' : '' ?>><?=$categoria->getNome()?></option>
                <?php endforeach; ?>
                <option value="nova_categoria">Nova Categoria</option>
            </select>
            <input type="text" class="form-control" name="categoriaNova" id="categoriaNova" value="">
        </div>
        <div class="row g-3 align-items-center mb-2">
            <input type="hidden" name="id" value="<?= isset($habilidade) ? $habilidade->getId() : '' ?>"/>
            <div class="col-md-12 form-floating">
                <input type="text" class="form-control" name="habilidade" id="habilidade" value="<?= isset($habilidade) ? $habilidade->getHabilidade() : '' ?>" required>
                <label for="habilidade" class="col-form-label">Habilidade</label>
            </div>
        </div>
        <div class="row gy-3 gy-md-4 overflow-hidden mt-4 mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Salvar</button>
                </div>
            </div>
        </div>
    </form>

    <script>
        let campoSelect = document.querySelector("#categoria");
        let campoInput = document.querySelector("#categoriaNova");

        campoSelect.addEventListener('change', function () {
            if (this.value === 'nova_categoria') {
                campoInput.style.display = '';
            } else {
                campoInput.style.display = 'none';
            }
        })
    </script>
</div>