<div class="container container-sm w-50">
    <form method="post" action="/filial/processacadastrar">
    <?php FlashMessage::getMessage() ?>
    <input type="hidden" name="filialId" value="<?= isset($filalId) ? $filialId->getId() : '' ?>"/>
    <input type="hidden" name="empresaId" value="<?= isset($empresaId) ? $empresaId->getEmpresa()->getId() : '' ?>"/>
    <div class="container container-sm w-75">
    <form method="post" action="/vaga/salvar">
        <input type="hidden" name="vagaId" value="<?= isset($vaga) ? $vaga->getId() : '' ?>"/>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-12 form-floating">
                <input type="text" class="form-control" name="titulo" id="titulo" value="<?= isset($vaga) ? $vaga->getTitulo() : '' ?>">
                <label for="titulo" class="col-form-label">Título</label>
            </div>
        </div>
        <div class="row g-3 align-items-center mb-2">
            <div class="col-md-4 form-floating">
                <input type="text" class="form-control" name="email" id="email" value="<?= isset($vaga) ? $vaga->getEmail() : '' ?>">
                <label for="email" class="col-form-label">Email</label>
            </div>
                </div>
            </div>
        </div>
    </div>            
        <div class="row gy-3 gy-md-4 overflow-hidden mt-4 mb-2">
            <div class="col-12">
                <div class="d-grid">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>