<div class="mx-auto max-w-3xl border p-4 m-14 rounded-xl bg-white">
    <form method="post" action="/filial/processaCadastrar">
        <input type="hidden" name="filialId" value="<?= isset($filial) ? $filial->getId() : '' ?>"/>
        <div class="flex space-x-2">
            <label class="form-control w-7/12">
                <div class="label">
                    <span class="label-text">Nome / Identificação</span>
                </div>
                <input type="text" name="filialNome" id="filialNome" required value="<?= isset($filial) ? $filial->getNome() : '' ?>" class="input input-bordered w-full"/>
            </label>
            <label class="form-control w-5/12">
                <div class="label">
                    <span class="label-text">CEP</span>
                </div>
                <input type="text" name="filialCep" id="filialCep" required minlength="8" maxlength="8" value="<?= isset($filial) ? $filial->getCep() : '' ?>" class="input input-bordered w-full" oninput="this.value = this.value.replace(/[^0-9]/g, '');"/>
                <div class="label">
                    <span class="label-text-alt">Exatos 8 caracteres - somente números</span>
                </div>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Logradouro</span>
                </div>
                <input type="email" name="filialLogradouro" id="filialLogradouro" value="<?= isset($filial) ? $filial->getLogradouro() : '' ?>" class="input input-bordered w-full"/>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-1/3">
                <div class="label">
                    <span class="label-text">Número</span>
                </div>
                <input type="text" name="filialNumero" id="filialNumero" value="<?= isset($filial) ? $filial->getNumero() : '' ?>" class="input input-bordered w-full"/>
            </label>
            <label class="form-control w-2/3">
                <div class="label">
                    <span class="label-text">Complemento</span>
                </div>
                <input type="text" name="filialComplemento" id="complemento" value="<?= isset($filial) ? $filial->getComplemento() : '' ?>" class="input input-bordered w-full"/>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-5/12">
                <div class="label">
                    <span class="label-text">Bairro</span>
                </div>
                <input type="text" name="filialBairro" id="filialBairro" value="<?= isset($filial) ? $filial->getBairro() : '' ?>" class="input input-bordered w-full"/>
            </label>
            <label class="form-control w-5/12">
                <div class="label">
                    <span class="label-text">Cidade</span>
                </div>
                <input type="text" name="filialCidade" id="filialCidade" required value="<?= isset($filial) ? $filial->getCidade() : '' ?>" class="input input-bordered w-full"/>
            </label>
            <label class="form-control w-2/12">
                <div class="label">
                    <span class="label-text">Estado</span>
                </div>
                <select class="select select-bordered" name="filialEstado" id="filialEstado" required>
                    <option value="" disabled selected>-</option>
                    <?php foreach (EstadoEnum::forSelect() as $indice => $valor): ?>
                        <option value="<?= $indice ?>" <?= !empty($filial) && $filial->getEstado() == $indice ? 'selected' : '' ?>><?= $valor ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
        </div>

        <div class="mt-6 flex items-center justify-end">
            <button class="btn btn-success btn-wide" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                </svg>

                Cadastrar
            </button>
        </div>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        let campo = document.querySelector("#filialCep");
        campo.addEventListener('blur', function () {
            if (campo.value.trim() == '') {
                return;
            }

            // let url = 'https://brasilapi.com.br/api/cep/v1/' + campo.value;
            let url = '/api/cep/?cep=' + campo.value;
            fetch(url)
                .then(response => {
                    if (response.status !== 200) {
                        throw new Error('Erro lalallaa')
                    }
                    return response.json()
                })
                .then(data => {
                    document.querySelector("#filialLogradouro").value = data.street;
                    document.querySelector("#filialBairro").value = data.neighborhood;
                    document.querySelector("#filialCidade").value = data.city;
                    document.querySelector("#filialEstado").value = data.state;

                })
                .catch(error => {
                    alert('CEP não encontrado');
                    campo.value = '';
                    document.querySelector("#filialLogradouro").value = '';
                    document.querySelector("#filialBairro").value = '';
                    document.querySelector("#filialCidade").value = '';
                    document.querySelector("#filialEstado").value = '';
                })
        });

    });
</script>