<?php /** @var Vaga $vaga */ ?>
<div id="vagas" class="flex flex-col px-4 py-10 gap-10 justify-center items-center">
    <h2 class="text-3xl font-bold">Proposta de contratação</h2>
</div>
<div class="mx-auto max-w-4xl border p-4 m-1 mb-20 rounded-xl bg-white">
    <form method="post" action="/propostas/salvar">
        <input type="hidden" name="vaga" id="vaga" value="<?= $_GET['id'] ?>">
        <input type="hidden" name="candidato" id="candidato" value="<?= $_GET['candidatoId'] ?>">
        <div class="flex space-x-2">
            <label class="form-control w-3/4">
                <div class="label">
                    <span class="label-text">Cargo</span>
                </div>
                <input type="text" class="input input-bordered w-full" min="0" name="cargo" id="cargo" value="<?= isset($vaga) ? $vaga->getTitulo() : '' ?>">
            </label>
            <label class="form-control w-1/4">
                <div class="label">
                    <span class="label-text">Salário</span>
                </div>
                <label class="input input-bordered flex items-center">
                    R$
                    <input type="number" class="input hover:border-0 focus:border-0 w-full text-right pe-0" min="0" name="salario" id="salario" value="<?= isset($vaga) ? $vaga->getSalario() : '' ?>">,00
                </label>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-1/4">
                <div class="label">
                    <span class="label-text">Regime de Contratação</span>
                </div>
                <select class="select select-bordered" name="regime_contratacao" id="regime_contratacao" required>
                    <option selected disabled value="">Selecione</option>
                    <?php foreach (RegimeContratacaoEnum::forSelect() as $indice => $valor): ?>
                        <option value="<?= $indice ?>" <?= !empty($vaga) && $vaga->getRegimeContratacao() == $indice ? 'selected' : '' ?>><?= $valor ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
            <label class="form-control w-1/4">
                <div class="label">
                    <span class="label-text">Regime de Trabalho</span>
                </div>
                <select class="select select-bordered" name="regime_trabalho" id="regime_trabalho" required>
                    <option selected disabled value="">Selecione</option>
                    <?php foreach (RegimeTrabalhoEnum::forSelect() as $indice => $valor): ?>
                        <option value="<?= $indice ?>" <?= !empty($vaga) && $vaga->getRegimeTrabalho() == $indice ? 'selected' : '' ?>><?= $valor ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
            <label class="form-control w-1/4">
                <div class="label">
                    <span class="label-text">Nível de Senioridade</span>
                </div>
                <select class="select select-bordered" name="nivel_senioridade" id="nivel_senioridade" required>
                    <option selected disabled value="">Selecione</option>
                    <?php foreach (NivelSenioridadeEnum::forSelect() as $indice => $valor): ?>
                        <option value="<?= $indice ?>" <?= !empty($vaga) && $vaga->getNivelSenioridade() == $indice ? 'selected' : '' ?>><?= $valor ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
            <label class="form-control w-1/4">
                <div class="label">
                    <span class="label-text">Nível hierárquico</span>
                </div>
                <select class="select select-bordered" name="nivel_hierarquico" id="nivel_hierarquico" required>
                    <option selected disabled value="">Selecione</option>
                    <?php foreach (NivelHierarquicoEnum::forSelect() as $indice => $valor): ?>
                        <option value="<?= $indice ?>" <?= !empty($vaga) && $vaga->getNivelHierarquico() == $indice ? 'selected' : '' ?>><?= $valor ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-full">
                <div class="label">
                    <span class="label-text">Endereço do local de trabalho</span>
                </div>
                <input type="text" class="input input-bordered w-full" name="endereco" id="endereco">
            </label>
        </div>
        <div class="flex space-x-2">
            <label class="form-control w-3/4">
                <div class="label">
                    <span class="label-text">Expediente</span>
                </div>
                <input type="text" class="input input-bordered w-full" name="expediente" id="expediente">
            </label>
            <label class="form-control w-1/4">
                <div class="label">
                    <span class="label-text">Data de início</span>
                </div>
                <input type="text" class="input input-bordered w-full" name="data_inicio" id="data_inicio">
            </label>
        </div>
        <div class="mt-6 flex items-center justify-end">
            <button class="btn btn-success btn-wide" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10"/>
                </svg>
                Enviar proposta
            </button>
        </div>
    </form>
</div>